# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
import directfs_pb2 as directfs__pb2


class DfsClientStub(object):
  """*
  DirectFS client configuration and status service.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Status = channel.unary_unary(
        '/directfs.v1.DfsClient/Status',
        request_serializer=directfs__pb2.DfsClientStatusRequest.SerializeToString,
        response_deserializer=directfs__pb2.DfsClientStatus.FromString,
        )
    self.ServerCreate = channel.unary_unary(
        '/directfs.v1.DfsClient/ServerCreate',
        request_serializer=directfs__pb2.DfsHost.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.ServerUpdate = channel.unary_unary(
        '/directfs.v1.DfsClient/ServerUpdate',
        request_serializer=directfs__pb2.DfsHost.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.ServerDelete = channel.unary_unary(
        '/directfs.v1.DfsClient/ServerDelete',
        request_serializer=directfs__pb2.DfsHost.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.ServerList = channel.unary_unary(
        '/directfs.v1.DfsClient/ServerList',
        request_serializer=directfs__pb2.DfsHostListQuery.SerializeToString,
        response_deserializer=directfs__pb2.DfsHostList.FromString,
        )
    self.VolumeCreate = channel.unary_unary(
        '/directfs.v1.DfsClient/VolumeCreate',
        request_serializer=directfs__pb2.DfsVolume.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.VolumeUpdate = channel.unary_unary(
        '/directfs.v1.DfsClient/VolumeUpdate',
        request_serializer=directfs__pb2.DfsVolume.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.VolumeDelete = channel.unary_unary(
        '/directfs.v1.DfsClient/VolumeDelete',
        request_serializer=directfs__pb2.DfsVolume.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.VolumeList = channel.unary_unary(
        '/directfs.v1.DfsClient/VolumeList',
        request_serializer=directfs__pb2.DfsVolumeListQuery.SerializeToString,
        response_deserializer=directfs__pb2.DfsVolumeList.FromString,
        )


class DfsClientServicer(object):
  """*
  DirectFS client configuration and status service.
  """

  def Status(self, request, context):
    """*
    Get program status.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerCreate(self, request, context):
    """*
    Add a remote host entry to be used by volumes.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerUpdate(self, request, context):
    """*
    Update a remote host entry to be used by volumes.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerDelete(self, request, context):
    """*
    Remove a remote host entry.

    This will likely result in any volumes using this host to
    become unconfigured. That has serious consequences.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerList(self, request, context):
    """*
    List configured host entries, optionally filtered via a DfsHostListQuery
    message.

    returns A DfsHostList message containing DfsHost messages,
    if any are available matching the filter.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeCreate(self, request, context):
    """*
    Create a volume on a remote host. The DfsHost matching the host id
    in the DfsVolume message must be configured for the volume to actually
    be configured on the DirectFS client.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeUpdate(self, request, context):
    """*
    Update a volume on a remote host. The DfsHost matching the host id
    in the DfsVolume message must be configured for the volume to actually
    be configured on the DirectFS client.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeDelete(self, request, context):
    """*
    Delete a volume previously configured by VolumeCreate.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeList(self, request, context):
    """*
    List configured volume entries, optionally filtered via a DfsVolumeListQuery
    message.

    returns A DfsVolumeList message containing DfsVolume messages,
    if any are available matching the filter.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DfsClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Status': grpc.unary_unary_rpc_method_handler(
          servicer.Status,
          request_deserializer=directfs__pb2.DfsClientStatusRequest.FromString,
          response_serializer=directfs__pb2.DfsClientStatus.SerializeToString,
      ),
      'ServerCreate': grpc.unary_unary_rpc_method_handler(
          servicer.ServerCreate,
          request_deserializer=directfs__pb2.DfsHost.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'ServerUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.ServerUpdate,
          request_deserializer=directfs__pb2.DfsHost.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'ServerDelete': grpc.unary_unary_rpc_method_handler(
          servicer.ServerDelete,
          request_deserializer=directfs__pb2.DfsHost.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'ServerList': grpc.unary_unary_rpc_method_handler(
          servicer.ServerList,
          request_deserializer=directfs__pb2.DfsHostListQuery.FromString,
          response_serializer=directfs__pb2.DfsHostList.SerializeToString,
      ),
      'VolumeCreate': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeCreate,
          request_deserializer=directfs__pb2.DfsVolume.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'VolumeUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeUpdate,
          request_deserializer=directfs__pb2.DfsVolume.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'VolumeDelete': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeDelete,
          request_deserializer=directfs__pb2.DfsVolume.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'VolumeList': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeList,
          request_deserializer=directfs__pb2.DfsVolumeListQuery.FromString,
          response_serializer=directfs__pb2.DfsVolumeList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'directfs.v1.DfsClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DfsServerStub(object):
  """*
  DirectFS server configuration and status service.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Status = channel.unary_unary(
        '/directfs.v1.DfsServer/Status',
        request_serializer=directfs__pb2.DfsServerStatusRequest.SerializeToString,
        response_deserializer=directfs__pb2.DfsServerStatus.FromString,
        )
    self.VolumeCreate = channel.unary_unary(
        '/directfs.v1.DfsServer/VolumeCreate',
        request_serializer=directfs__pb2.DfsVolume.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.VolumeUpdate = channel.unary_unary(
        '/directfs.v1.DfsServer/VolumeUpdate',
        request_serializer=directfs__pb2.DfsVolume.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.VolumeDelete = channel.unary_unary(
        '/directfs.v1.DfsServer/VolumeDelete',
        request_serializer=directfs__pb2.DfsVolume.SerializeToString,
        response_deserializer=common__pb2.RpcResult.FromString,
        )
    self.VolumeList = channel.unary_unary(
        '/directfs.v1.DfsServer/VolumeList',
        request_serializer=directfs__pb2.DfsVolumeListQuery.SerializeToString,
        response_deserializer=directfs__pb2.DfsVolumeList.FromString,
        )


class DfsServerServicer(object):
  """*
  DirectFS server configuration and status service.
  """

  def Status(self, request, context):
    """*
    Get program status.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeCreate(self, request, context):
    """*
    Create a volume to be served via DFS. Currently does nothing, but should still
    be performed as in the near future it will certainly be required.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeUpdate(self, request, context):
    """*
    Update a volume to be served via DFS. Currently does nothing, but should still
    be performed as in the near future it will certainly be required.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeDelete(self, request, context):
    """*
    Delete a volume to be served via DFS. Currently does nothing, but should still
    be performed as in the near future it will certainly be required.

    returns RpcResult
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VolumeList(self, request, context):
    """*
    List configured volume entries, optionally filtered via a DfsVolumeListQuery
    message.

    returns a stream of DfsVolume messages, if any are available matching the filter.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DfsServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Status': grpc.unary_unary_rpc_method_handler(
          servicer.Status,
          request_deserializer=directfs__pb2.DfsServerStatusRequest.FromString,
          response_serializer=directfs__pb2.DfsServerStatus.SerializeToString,
      ),
      'VolumeCreate': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeCreate,
          request_deserializer=directfs__pb2.DfsVolume.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'VolumeUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeUpdate,
          request_deserializer=directfs__pb2.DfsVolume.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'VolumeDelete': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeDelete,
          request_deserializer=directfs__pb2.DfsVolume.FromString,
          response_serializer=common__pb2.RpcResult.SerializeToString,
      ),
      'VolumeList': grpc.unary_unary_rpc_method_handler(
          servicer.VolumeList,
          request_deserializer=directfs__pb2.DfsVolumeListQuery.FromString,
          response_serializer=directfs__pb2.DfsVolumeList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'directfs.v1.DfsServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
