// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package v1 // import "code.storageos.net/storageos/service/common/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	// Status code not set.
	StatusCode_STATUS_NONE StatusCode = 0
	// Generic 'no problem' response.
	StatusCode_STATUS_OK StatusCode = 200
	// Accepted, but might not take effect immediately.
	StatusCode_STATUS_ACCEPTED StatusCode = 202
	// Resource created.
	StatusCode_STATUS_CREATED StatusCode = 201
	// Generic 'huh?'.
	StatusCode_STATUS_BAD_REQUEST StatusCode = 400
	// Not permitted. We're unlikely to use this, it indicates authorization will help.
	StatusCode_STATUS_UNAUTHORIZED StatusCode = 401
	// Not allowed, authorization isn't the issue.
	StatusCode_STATUS_FORBIDDEN StatusCode = 403
	// Resource not found.
	StatusCode_STATUS_NOT_FOUND StatusCode = 404
	// Operation would cause a conflict somewhere.
	StatusCode_STATUS_CONFLICT StatusCode = 409
	// General serious failure.
	StatusCode_STATUS_SERVER_ERROR StatusCode = 500
)

var StatusCode_name = map[int32]string{
	0:   "STATUS_NONE",
	200: "STATUS_OK",
	202: "STATUS_ACCEPTED",
	201: "STATUS_CREATED",
	400: "STATUS_BAD_REQUEST",
	401: "STATUS_UNAUTHORIZED",
	403: "STATUS_FORBIDDEN",
	404: "STATUS_NOT_FOUND",
	409: "STATUS_CONFLICT",
	500: "STATUS_SERVER_ERROR",
}
var StatusCode_value = map[string]int32{
	"STATUS_NONE":         0,
	"STATUS_OK":           200,
	"STATUS_ACCEPTED":     202,
	"STATUS_CREATED":      201,
	"STATUS_BAD_REQUEST":  400,
	"STATUS_UNAUTHORIZED": 401,
	"STATUS_FORBIDDEN":    403,
	"STATUS_NOT_FOUND":    404,
	"STATUS_CONFLICT":     409,
	"STATUS_SERVER_ERROR": 500,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{0}
}

type ConfigGetStatus int32

const (
	ConfigGetStatus_GET_NONE    ConfigGetStatus = 0
	ConfigGetStatus_GET_OK      ConfigGetStatus = 1
	ConfigGetStatus_GET_MISSING ConfigGetStatus = 2
	ConfigGetStatus_GET_FAILED  ConfigGetStatus = 3
)

var ConfigGetStatus_name = map[int32]string{
	0: "GET_NONE",
	1: "GET_OK",
	2: "GET_MISSING",
	3: "GET_FAILED",
}
var ConfigGetStatus_value = map[string]int32{
	"GET_NONE":    0,
	"GET_OK":      1,
	"GET_MISSING": 2,
	"GET_FAILED":  3,
}

func (x ConfigGetStatus) String() string {
	return proto.EnumName(ConfigGetStatus_name, int32(x))
}
func (ConfigGetStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{1}
}

type ConfigUpdateStatus int32

const (
	ConfigUpdateStatus_SET_NONE      ConfigUpdateStatus = 0
	ConfigUpdateStatus_SET_OK        ConfigUpdateStatus = 1
	ConfigUpdateStatus_SET_IMMUTABLE ConfigUpdateStatus = 2
	ConfigUpdateStatus_SET_FAILED    ConfigUpdateStatus = 3
	ConfigUpdateStatus_SET_READ_ONLY ConfigUpdateStatus = 4
)

var ConfigUpdateStatus_name = map[int32]string{
	0: "SET_NONE",
	1: "SET_OK",
	2: "SET_IMMUTABLE",
	3: "SET_FAILED",
	4: "SET_READ_ONLY",
}
var ConfigUpdateStatus_value = map[string]int32{
	"SET_NONE":      0,
	"SET_OK":        1,
	"SET_IMMUTABLE": 2,
	"SET_FAILED":    3,
	"SET_READ_ONLY": 4,
}

func (x ConfigUpdateStatus) String() string {
	return proto.EnumName(ConfigUpdateStatus_name, int32(x))
}
func (ConfigUpdateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{2}
}

type VolumeCrypto_VolumeCryptoState int32

const (
	VolumeCrypto_VCS_NONE            VolumeCrypto_VolumeCryptoState = 0
	VolumeCrypto_VCS_FULLY_ENCRYPTED VolumeCrypto_VolumeCryptoState = 1
)

var VolumeCrypto_VolumeCryptoState_name = map[int32]string{
	0: "VCS_NONE",
	1: "VCS_FULLY_ENCRYPTED",
}
var VolumeCrypto_VolumeCryptoState_value = map[string]int32{
	"VCS_NONE":            0,
	"VCS_FULLY_ENCRYPTED": 1,
}

func (x VolumeCrypto_VolumeCryptoState) String() string {
	return proto.EnumName(VolumeCrypto_VolumeCryptoState_name, int32(x))
}
func (VolumeCrypto_VolumeCryptoState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{8, 0}
}

type DaemonStatus_ProgramState int32

const (
	DaemonStatus_DS_NONE     DaemonStatus_ProgramState = 0
	DaemonStatus_DS_STARTING DaemonStatus_ProgramState = 1
	DaemonStatus_DS_READY    DaemonStatus_ProgramState = 2
	DaemonStatus_DS_STOPPING DaemonStatus_ProgramState = 3
	DaemonStatus_DS_STOPPED  DaemonStatus_ProgramState = 4
	DaemonStatus_DS_ERROR    DaemonStatus_ProgramState = 5
	DaemonStatus_DS_CRITICAL DaemonStatus_ProgramState = 6
)

var DaemonStatus_ProgramState_name = map[int32]string{
	0: "DS_NONE",
	1: "DS_STARTING",
	2: "DS_READY",
	3: "DS_STOPPING",
	4: "DS_STOPPED",
	5: "DS_ERROR",
	6: "DS_CRITICAL",
}
var DaemonStatus_ProgramState_value = map[string]int32{
	"DS_NONE":     0,
	"DS_STARTING": 1,
	"DS_READY":    2,
	"DS_STOPPING": 3,
	"DS_STOPPED":  4,
	"DS_ERROR":    5,
	"DS_CRITICAL": 6,
}

func (x DaemonStatus_ProgramState) String() string {
	return proto.EnumName(DaemonStatus_ProgramState_name, int32(x))
}
func (DaemonStatus_ProgramState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{9, 0}
}

type StatsListQuery_Type int32

const (
	// For requesting volume stats.
	StatsListQuery_VOLUME StatsListQuery_Type = 0
	// For requesting node stats.
	StatsListQuery_NODE StatsListQuery_Type = 1
)

var StatsListQuery_Type_name = map[int32]string{
	0: "VOLUME",
	1: "NODE",
}
var StatsListQuery_Type_value = map[string]int32{
	"VOLUME": 0,
	"NODE":   1,
}

func (x StatsListQuery_Type) String() string {
	return proto.EnumName(StatsListQuery_Type_name, int32(x))
}
func (StatsListQuery_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{25, 0}
}

type RpcResult struct {
	// Whether or not the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// If the operation was not successful, this is an explanatory message.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// An HTTP-like status code.
	Code                 StatusCode `protobuf:"varint,3,opt,name=code,proto3,enum=common.v1.StatusCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RpcResult) Reset()         { *m = RpcResult{} }
func (m *RpcResult) String() string { return proto.CompactTextString(m) }
func (*RpcResult) ProtoMessage()    {}
func (*RpcResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{0}
}
func (m *RpcResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResult.Unmarshal(m, b)
}
func (m *RpcResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResult.Marshal(b, m, deterministic)
}
func (dst *RpcResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResult.Merge(dst, src)
}
func (m *RpcResult) XXX_Size() int {
	return xxx_messageInfo_RpcResult.Size(m)
}
func (m *RpcResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResult.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResult proto.InternalMessageInfo

func (m *RpcResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *RpcResult) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *RpcResult) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_STATUS_NONE
}

type DataplaneCommon struct {
	// UUID. An opaque string used by the controlplane as a unique ID.
	Uuid string `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// The config 'revision', an opaque integer used by the controlplane to identify a configuration iteration.
	// This is deliberately matched to the revision field in etcd ResponseHeader.revision.
	Revision int64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	// Latch for the versioning system. If true, updates will fail unless the generation of the change
	// is newer than the existing value.
	Versioned            bool     `protobuf:"varint,5,opt,name=versioned,proto3" json:"versioned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataplaneCommon) Reset()         { *m = DataplaneCommon{} }
func (m *DataplaneCommon) String() string { return proto.CompactTextString(m) }
func (*DataplaneCommon) ProtoMessage()    {}
func (*DataplaneCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{1}
}
func (m *DataplaneCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataplaneCommon.Unmarshal(m, b)
}
func (m *DataplaneCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataplaneCommon.Marshal(b, m, deterministic)
}
func (dst *DataplaneCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataplaneCommon.Merge(dst, src)
}
func (m *DataplaneCommon) XXX_Size() int {
	return xxx_messageInfo_DataplaneCommon.Size(m)
}
func (m *DataplaneCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_DataplaneCommon.DiscardUnknown(m)
}

var xxx_messageInfo_DataplaneCommon proto.InternalMessageInfo

func (m *DataplaneCommon) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DataplaneCommon) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *DataplaneCommon) GetVersioned() bool {
	if m != nil {
		return m.Versioned
	}
	return false
}

type Aes256Key struct {
	// 32 bytes (256 bits) of AES-256 key as raw bytes.
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Aes256Key) Reset()         { *m = Aes256Key{} }
func (m *Aes256Key) String() string { return proto.CompactTextString(m) }
func (*Aes256Key) ProtoMessage()    {}
func (*Aes256Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{2}
}
func (m *Aes256Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aes256Key.Unmarshal(m, b)
}
func (m *Aes256Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aes256Key.Marshal(b, m, deterministic)
}
func (dst *Aes256Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aes256Key.Merge(dst, src)
}
func (m *Aes256Key) XXX_Size() int {
	return xxx_messageInfo_Aes256Key.Size(m)
}
func (m *Aes256Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Aes256Key.DiscardUnknown(m)
}

var xxx_messageInfo_Aes256Key proto.InternalMessageInfo

func (m *Aes256Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Aes256IV struct {
	// 32 bytes (256 bits) of IV as raw bytes.
	Iv                   []byte   `protobuf:"bytes,1,opt,name=iv,proto3" json:"iv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Aes256IV) Reset()         { *m = Aes256IV{} }
func (m *Aes256IV) String() string { return proto.CompactTextString(m) }
func (*Aes256IV) ProtoMessage()    {}
func (*Aes256IV) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{3}
}
func (m *Aes256IV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aes256IV.Unmarshal(m, b)
}
func (m *Aes256IV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aes256IV.Marshal(b, m, deterministic)
}
func (dst *Aes256IV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aes256IV.Merge(dst, src)
}
func (m *Aes256IV) XXX_Size() int {
	return xxx_messageInfo_Aes256IV.Size(m)
}
func (m *Aes256IV) XXX_DiscardUnknown() {
	xxx_messageInfo_Aes256IV.DiscardUnknown(m)
}

var xxx_messageInfo_Aes256IV proto.InternalMessageInfo

func (m *Aes256IV) GetIv() []byte {
	if m != nil {
		return m.Iv
	}
	return nil
}

type XtsAes256Key struct {
	// 64 bytes (512 bits) of key data for XTS-AES 256 as raw bytes.
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XtsAes256Key) Reset()         { *m = XtsAes256Key{} }
func (m *XtsAes256Key) String() string { return proto.CompactTextString(m) }
func (*XtsAes256Key) ProtoMessage()    {}
func (*XtsAes256Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{4}
}
func (m *XtsAes256Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XtsAes256Key.Unmarshal(m, b)
}
func (m *XtsAes256Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XtsAes256Key.Marshal(b, m, deterministic)
}
func (dst *XtsAes256Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XtsAes256Key.Merge(dst, src)
}
func (m *XtsAes256Key) XXX_Size() int {
	return xxx_messageInfo_XtsAes256Key.Size(m)
}
func (m *XtsAes256Key) XXX_DiscardUnknown() {
	xxx_messageInfo_XtsAes256Key.DiscardUnknown(m)
}

var xxx_messageInfo_XtsAes256Key proto.InternalMessageInfo

func (m *XtsAes256Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type EncryptedXtsAesKey struct {
	// 64 bytes (512 bits) + up to 16 bytes of key data + padding for an
	// encrypted XTS-AES 256 key, as raw data.
	Ekey                 []byte   `protobuf:"bytes,1,opt,name=ekey,proto3" json:"ekey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedXtsAesKey) Reset()         { *m = EncryptedXtsAesKey{} }
func (m *EncryptedXtsAesKey) String() string { return proto.CompactTextString(m) }
func (*EncryptedXtsAesKey) ProtoMessage()    {}
func (*EncryptedXtsAesKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{5}
}
func (m *EncryptedXtsAesKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedXtsAesKey.Unmarshal(m, b)
}
func (m *EncryptedXtsAesKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedXtsAesKey.Marshal(b, m, deterministic)
}
func (dst *EncryptedXtsAesKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedXtsAesKey.Merge(dst, src)
}
func (m *EncryptedXtsAesKey) XXX_Size() int {
	return xxx_messageInfo_EncryptedXtsAesKey.Size(m)
}
func (m *EncryptedXtsAesKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedXtsAesKey.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedXtsAesKey proto.InternalMessageInfo

func (m *EncryptedXtsAesKey) GetEkey() []byte {
	if m != nil {
		return m.Ekey
	}
	return nil
}

type XtsKeyHMAC struct {
	// 64 bytes (512 bits) of HMAC data.
	Hmac                 []byte   `protobuf:"bytes,1,opt,name=hmac,proto3" json:"hmac,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XtsKeyHMAC) Reset()         { *m = XtsKeyHMAC{} }
func (m *XtsKeyHMAC) String() string { return proto.CompactTextString(m) }
func (*XtsKeyHMAC) ProtoMessage()    {}
func (*XtsKeyHMAC) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{6}
}
func (m *XtsKeyHMAC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XtsKeyHMAC.Unmarshal(m, b)
}
func (m *XtsKeyHMAC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XtsKeyHMAC.Marshal(b, m, deterministic)
}
func (dst *XtsKeyHMAC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XtsKeyHMAC.Merge(dst, src)
}
func (m *XtsKeyHMAC) XXX_Size() int {
	return xxx_messageInfo_XtsKeyHMAC.Size(m)
}
func (m *XtsKeyHMAC) XXX_DiscardUnknown() {
	xxx_messageInfo_XtsKeyHMAC.DiscardUnknown(m)
}

var xxx_messageInfo_XtsKeyHMAC proto.InternalMessageInfo

func (m *XtsKeyHMAC) GetHmac() []byte {
	if m != nil {
		return m.Hmac
	}
	return nil
}

type VolumeKeySet struct {
	// The AES-XTS 256 volume master key.
	Vmk                  *XtsAes256Key `protobuf:"bytes,1,opt,name=vmk,proto3" json:"vmk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VolumeKeySet) Reset()         { *m = VolumeKeySet{} }
func (m *VolumeKeySet) String() string { return proto.CompactTextString(m) }
func (*VolumeKeySet) ProtoMessage()    {}
func (*VolumeKeySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{7}
}
func (m *VolumeKeySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeKeySet.Unmarshal(m, b)
}
func (m *VolumeKeySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeKeySet.Marshal(b, m, deterministic)
}
func (dst *VolumeKeySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeKeySet.Merge(dst, src)
}
func (m *VolumeKeySet) XXX_Size() int {
	return xxx_messageInfo_VolumeKeySet.Size(m)
}
func (m *VolumeKeySet) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeKeySet.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeKeySet proto.InternalMessageInfo

func (m *VolumeKeySet) GetVmk() *XtsAes256Key {
	if m != nil {
		return m.Vmk
	}
	return nil
}

type VolumeCrypto struct {
	// The crypto stepping version. Current version is 1.
	CryptoVersion uint32 `protobuf:"varint,2,opt,name=crypto_version,json=cryptoVersion,proto3" json:"crypto_version,omitempty"`
	// The current crypto state for this volume.
	CryptoState VolumeCrypto_VolumeCryptoState `protobuf:"varint,3,opt,name=crypto_state,json=cryptoState,proto3,enum=common.v1.VolumeCrypto_VolumeCryptoState" json:"crypto_state,omitempty"`
	// True iff the keyset contains valid key data.
	// Should only be set on create, and is likely to trigger validation errors
	// if set at other times.
	//
	// The dataplane servers will not reflect key data.
	KeysetPresent bool `protobuf:"varint,5,opt,name=keyset_present,json=keysetPresent,proto3" json:"keyset_present,omitempty"`
	// The set of keys required to use the volume.
	Keyset               *VolumeKeySet `protobuf:"bytes,4,opt,name=keyset,proto3" json:"keyset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VolumeCrypto) Reset()         { *m = VolumeCrypto{} }
func (m *VolumeCrypto) String() string { return proto.CompactTextString(m) }
func (*VolumeCrypto) ProtoMessage()    {}
func (*VolumeCrypto) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{8}
}
func (m *VolumeCrypto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeCrypto.Unmarshal(m, b)
}
func (m *VolumeCrypto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeCrypto.Marshal(b, m, deterministic)
}
func (dst *VolumeCrypto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeCrypto.Merge(dst, src)
}
func (m *VolumeCrypto) XXX_Size() int {
	return xxx_messageInfo_VolumeCrypto.Size(m)
}
func (m *VolumeCrypto) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeCrypto.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeCrypto proto.InternalMessageInfo

func (m *VolumeCrypto) GetCryptoVersion() uint32 {
	if m != nil {
		return m.CryptoVersion
	}
	return 0
}

func (m *VolumeCrypto) GetCryptoState() VolumeCrypto_VolumeCryptoState {
	if m != nil {
		return m.CryptoState
	}
	return VolumeCrypto_VCS_NONE
}

func (m *VolumeCrypto) GetKeysetPresent() bool {
	if m != nil {
		return m.KeysetPresent
	}
	return false
}

func (m *VolumeCrypto) GetKeyset() *VolumeKeySet {
	if m != nil {
		return m.Keyset
	}
	return nil
}

type DaemonStatus struct {
	ProgramState         DaemonStatus_ProgramState `protobuf:"varint,1,opt,name=program_state,json=programState,proto3,enum=common.v1.DaemonStatus_ProgramState" json:"program_state,omitempty"`
	ProgramStateMessage  string                    `protobuf:"bytes,2,opt,name=program_state_message,json=programStateMessage,proto3" json:"program_state_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DaemonStatus) Reset()         { *m = DaemonStatus{} }
func (m *DaemonStatus) String() string { return proto.CompactTextString(m) }
func (*DaemonStatus) ProtoMessage()    {}
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{9}
}
func (m *DaemonStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DaemonStatus.Unmarshal(m, b)
}
func (m *DaemonStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DaemonStatus.Marshal(b, m, deterministic)
}
func (dst *DaemonStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DaemonStatus.Merge(dst, src)
}
func (m *DaemonStatus) XXX_Size() int {
	return xxx_messageInfo_DaemonStatus.Size(m)
}
func (m *DaemonStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DaemonStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DaemonStatus proto.InternalMessageInfo

func (m *DaemonStatus) GetProgramState() DaemonStatus_ProgramState {
	if m != nil {
		return m.ProgramState
	}
	return DaemonStatus_DS_NONE
}

func (m *DaemonStatus) GetProgramStateMessage() string {
	if m != nil {
		return m.ProgramStateMessage
	}
	return ""
}

type ConfigUpdateReply struct {
	Status               ConfigUpdateStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.v1.ConfigUpdateStatus" json:"status,omitempty"`
	Result               *RpcResult         `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ConfigUpdateReply) Reset()         { *m = ConfigUpdateReply{} }
func (m *ConfigUpdateReply) String() string { return proto.CompactTextString(m) }
func (*ConfigUpdateReply) ProtoMessage()    {}
func (*ConfigUpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{10}
}
func (m *ConfigUpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUpdateReply.Unmarshal(m, b)
}
func (m *ConfigUpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUpdateReply.Marshal(b, m, deterministic)
}
func (dst *ConfigUpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUpdateReply.Merge(dst, src)
}
func (m *ConfigUpdateReply) XXX_Size() int {
	return xxx_messageInfo_ConfigUpdateReply.Size(m)
}
func (m *ConfigUpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUpdateReply proto.InternalMessageInfo

func (m *ConfigUpdateReply) GetStatus() ConfigUpdateStatus {
	if m != nil {
		return m.Status
	}
	return ConfigUpdateStatus_SET_NONE
}

func (m *ConfigUpdateReply) GetResult() *RpcResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ConfigBool struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                bool     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigBool) Reset()         { *m = ConfigBool{} }
func (m *ConfigBool) String() string { return proto.CompactTextString(m) }
func (*ConfigBool) ProtoMessage()    {}
func (*ConfigBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{11}
}
func (m *ConfigBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBool.Unmarshal(m, b)
}
func (m *ConfigBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBool.Marshal(b, m, deterministic)
}
func (dst *ConfigBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBool.Merge(dst, src)
}
func (m *ConfigBool) XXX_Size() int {
	return xxx_messageInfo_ConfigBool.Size(m)
}
func (m *ConfigBool) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBool.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBool proto.InternalMessageInfo

func (m *ConfigBool) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigBool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type ConfigGetBoolReply struct {
	Status               ConfigGetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.v1.ConfigGetStatus" json:"status,omitempty"`
	Result               *RpcResult      `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Item                 *ConfigBool     `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigGetBoolReply) Reset()         { *m = ConfigGetBoolReply{} }
func (m *ConfigGetBoolReply) String() string { return proto.CompactTextString(m) }
func (*ConfigGetBoolReply) ProtoMessage()    {}
func (*ConfigGetBoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{12}
}
func (m *ConfigGetBoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGetBoolReply.Unmarshal(m, b)
}
func (m *ConfigGetBoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGetBoolReply.Marshal(b, m, deterministic)
}
func (dst *ConfigGetBoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGetBoolReply.Merge(dst, src)
}
func (m *ConfigGetBoolReply) XXX_Size() int {
	return xxx_messageInfo_ConfigGetBoolReply.Size(m)
}
func (m *ConfigGetBoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGetBoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGetBoolReply proto.InternalMessageInfo

func (m *ConfigGetBoolReply) GetStatus() ConfigGetStatus {
	if m != nil {
		return m.Status
	}
	return ConfigGetStatus_GET_NONE
}

func (m *ConfigGetBoolReply) GetResult() *RpcResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ConfigGetBoolReply) GetItem() *ConfigBool {
	if m != nil {
		return m.Item
	}
	return nil
}

type ConfigBoolList struct {
	Items                []*ConfigBool `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConfigBoolList) Reset()         { *m = ConfigBoolList{} }
func (m *ConfigBoolList) String() string { return proto.CompactTextString(m) }
func (*ConfigBoolList) ProtoMessage()    {}
func (*ConfigBoolList) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{13}
}
func (m *ConfigBoolList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigBoolList.Unmarshal(m, b)
}
func (m *ConfigBoolList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigBoolList.Marshal(b, m, deterministic)
}
func (dst *ConfigBoolList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigBoolList.Merge(dst, src)
}
func (m *ConfigBoolList) XXX_Size() int {
	return xxx_messageInfo_ConfigBoolList.Size(m)
}
func (m *ConfigBoolList) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigBoolList.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigBoolList proto.InternalMessageInfo

func (m *ConfigBoolList) GetItems() []*ConfigBool {
	if m != nil {
		return m.Items
	}
	return nil
}

type ConfigUint32 struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                uint32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigUint32) Reset()         { *m = ConfigUint32{} }
func (m *ConfigUint32) String() string { return proto.CompactTextString(m) }
func (*ConfigUint32) ProtoMessage()    {}
func (*ConfigUint32) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{14}
}
func (m *ConfigUint32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUint32.Unmarshal(m, b)
}
func (m *ConfigUint32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUint32.Marshal(b, m, deterministic)
}
func (dst *ConfigUint32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUint32.Merge(dst, src)
}
func (m *ConfigUint32) XXX_Size() int {
	return xxx_messageInfo_ConfigUint32.Size(m)
}
func (m *ConfigUint32) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUint32.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUint32 proto.InternalMessageInfo

func (m *ConfigUint32) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigUint32) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ConfigGetUint32Reply struct {
	Status               ConfigGetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.v1.ConfigGetStatus" json:"status,omitempty"`
	Result               *RpcResult      `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Item                 *ConfigUint32   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigGetUint32Reply) Reset()         { *m = ConfigGetUint32Reply{} }
func (m *ConfigGetUint32Reply) String() string { return proto.CompactTextString(m) }
func (*ConfigGetUint32Reply) ProtoMessage()    {}
func (*ConfigGetUint32Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{15}
}
func (m *ConfigGetUint32Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGetUint32Reply.Unmarshal(m, b)
}
func (m *ConfigGetUint32Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGetUint32Reply.Marshal(b, m, deterministic)
}
func (dst *ConfigGetUint32Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGetUint32Reply.Merge(dst, src)
}
func (m *ConfigGetUint32Reply) XXX_Size() int {
	return xxx_messageInfo_ConfigGetUint32Reply.Size(m)
}
func (m *ConfigGetUint32Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGetUint32Reply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGetUint32Reply proto.InternalMessageInfo

func (m *ConfigGetUint32Reply) GetStatus() ConfigGetStatus {
	if m != nil {
		return m.Status
	}
	return ConfigGetStatus_GET_NONE
}

func (m *ConfigGetUint32Reply) GetResult() *RpcResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ConfigGetUint32Reply) GetItem() *ConfigUint32 {
	if m != nil {
		return m.Item
	}
	return nil
}

type ConfigUint32List struct {
	Items                []*ConfigUint32 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigUint32List) Reset()         { *m = ConfigUint32List{} }
func (m *ConfigUint32List) String() string { return proto.CompactTextString(m) }
func (*ConfigUint32List) ProtoMessage()    {}
func (*ConfigUint32List) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{16}
}
func (m *ConfigUint32List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUint32List.Unmarshal(m, b)
}
func (m *ConfigUint32List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUint32List.Marshal(b, m, deterministic)
}
func (dst *ConfigUint32List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUint32List.Merge(dst, src)
}
func (m *ConfigUint32List) XXX_Size() int {
	return xxx_messageInfo_ConfigUint32List.Size(m)
}
func (m *ConfigUint32List) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUint32List.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUint32List proto.InternalMessageInfo

func (m *ConfigUint32List) GetItems() []*ConfigUint32 {
	if m != nil {
		return m.Items
	}
	return nil
}

type ConfigUint64 struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigUint64) Reset()         { *m = ConfigUint64{} }
func (m *ConfigUint64) String() string { return proto.CompactTextString(m) }
func (*ConfigUint64) ProtoMessage()    {}
func (*ConfigUint64) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{17}
}
func (m *ConfigUint64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUint64.Unmarshal(m, b)
}
func (m *ConfigUint64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUint64.Marshal(b, m, deterministic)
}
func (dst *ConfigUint64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUint64.Merge(dst, src)
}
func (m *ConfigUint64) XXX_Size() int {
	return xxx_messageInfo_ConfigUint64.Size(m)
}
func (m *ConfigUint64) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUint64.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUint64 proto.InternalMessageInfo

func (m *ConfigUint64) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigUint64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ConfigGetUint64Reply struct {
	Status               ConfigGetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.v1.ConfigGetStatus" json:"status,omitempty"`
	Result               *RpcResult      `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Item                 *ConfigUint64   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigGetUint64Reply) Reset()         { *m = ConfigGetUint64Reply{} }
func (m *ConfigGetUint64Reply) String() string { return proto.CompactTextString(m) }
func (*ConfigGetUint64Reply) ProtoMessage()    {}
func (*ConfigGetUint64Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{18}
}
func (m *ConfigGetUint64Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGetUint64Reply.Unmarshal(m, b)
}
func (m *ConfigGetUint64Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGetUint64Reply.Marshal(b, m, deterministic)
}
func (dst *ConfigGetUint64Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGetUint64Reply.Merge(dst, src)
}
func (m *ConfigGetUint64Reply) XXX_Size() int {
	return xxx_messageInfo_ConfigGetUint64Reply.Size(m)
}
func (m *ConfigGetUint64Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGetUint64Reply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGetUint64Reply proto.InternalMessageInfo

func (m *ConfigGetUint64Reply) GetStatus() ConfigGetStatus {
	if m != nil {
		return m.Status
	}
	return ConfigGetStatus_GET_NONE
}

func (m *ConfigGetUint64Reply) GetResult() *RpcResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ConfigGetUint64Reply) GetItem() *ConfigUint64 {
	if m != nil {
		return m.Item
	}
	return nil
}

type ConfigUint64List struct {
	Items                []*ConfigUint64 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigUint64List) Reset()         { *m = ConfigUint64List{} }
func (m *ConfigUint64List) String() string { return proto.CompactTextString(m) }
func (*ConfigUint64List) ProtoMessage()    {}
func (*ConfigUint64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{19}
}
func (m *ConfigUint64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUint64List.Unmarshal(m, b)
}
func (m *ConfigUint64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUint64List.Marshal(b, m, deterministic)
}
func (dst *ConfigUint64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUint64List.Merge(dst, src)
}
func (m *ConfigUint64List) XXX_Size() int {
	return xxx_messageInfo_ConfigUint64List.Size(m)
}
func (m *ConfigUint64List) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUint64List.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUint64List proto.InternalMessageInfo

func (m *ConfigUint64List) GetItems() []*ConfigUint64 {
	if m != nil {
		return m.Items
	}
	return nil
}

type ConfigString struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigString) Reset()         { *m = ConfigString{} }
func (m *ConfigString) String() string { return proto.CompactTextString(m) }
func (*ConfigString) ProtoMessage()    {}
func (*ConfigString) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{20}
}
func (m *ConfigString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigString.Unmarshal(m, b)
}
func (m *ConfigString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigString.Marshal(b, m, deterministic)
}
func (dst *ConfigString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigString.Merge(dst, src)
}
func (m *ConfigString) XXX_Size() int {
	return xxx_messageInfo_ConfigString.Size(m)
}
func (m *ConfigString) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigString.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigString proto.InternalMessageInfo

func (m *ConfigString) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ConfigString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ConfigGetStringReply struct {
	Status               ConfigGetStatus `protobuf:"varint,1,opt,name=status,proto3,enum=common.v1.ConfigGetStatus" json:"status,omitempty"`
	Result               *RpcResult      `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Item                 *ConfigString   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigGetStringReply) Reset()         { *m = ConfigGetStringReply{} }
func (m *ConfigGetStringReply) String() string { return proto.CompactTextString(m) }
func (*ConfigGetStringReply) ProtoMessage()    {}
func (*ConfigGetStringReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{21}
}
func (m *ConfigGetStringReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigGetStringReply.Unmarshal(m, b)
}
func (m *ConfigGetStringReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigGetStringReply.Marshal(b, m, deterministic)
}
func (dst *ConfigGetStringReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigGetStringReply.Merge(dst, src)
}
func (m *ConfigGetStringReply) XXX_Size() int {
	return xxx_messageInfo_ConfigGetStringReply.Size(m)
}
func (m *ConfigGetStringReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigGetStringReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigGetStringReply proto.InternalMessageInfo

func (m *ConfigGetStringReply) GetStatus() ConfigGetStatus {
	if m != nil {
		return m.Status
	}
	return ConfigGetStatus_GET_NONE
}

func (m *ConfigGetStringReply) GetResult() *RpcResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ConfigGetStringReply) GetItem() *ConfigString {
	if m != nil {
		return m.Item
	}
	return nil
}

type ConfigStringList struct {
	Items                []*ConfigString `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConfigStringList) Reset()         { *m = ConfigStringList{} }
func (m *ConfigStringList) String() string { return proto.CompactTextString(m) }
func (*ConfigStringList) ProtoMessage()    {}
func (*ConfigStringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{22}
}
func (m *ConfigStringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigStringList.Unmarshal(m, b)
}
func (m *ConfigStringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigStringList.Marshal(b, m, deterministic)
}
func (dst *ConfigStringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigStringList.Merge(dst, src)
}
func (m *ConfigStringList) XXX_Size() int {
	return xxx_messageInfo_ConfigStringList.Size(m)
}
func (m *ConfigStringList) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigStringList.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigStringList proto.InternalMessageInfo

func (m *ConfigStringList) GetItems() []*ConfigString {
	if m != nil {
		return m.Items
	}
	return nil
}

type ConfigKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigKey) Reset()         { *m = ConfigKey{} }
func (m *ConfigKey) String() string { return proto.CompactTextString(m) }
func (*ConfigKey) ProtoMessage()    {}
func (*ConfigKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{23}
}
func (m *ConfigKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigKey.Unmarshal(m, b)
}
func (m *ConfigKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigKey.Marshal(b, m, deterministic)
}
func (dst *ConfigKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigKey.Merge(dst, src)
}
func (m *ConfigKey) XXX_Size() int {
	return xxx_messageInfo_ConfigKey.Size(m)
}
func (m *ConfigKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigKey.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigKey proto.InternalMessageInfo

func (m *ConfigKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ConfigListQuery struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigListQuery) Reset()         { *m = ConfigListQuery{} }
func (m *ConfigListQuery) String() string { return proto.CompactTextString(m) }
func (*ConfigListQuery) ProtoMessage()    {}
func (*ConfigListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{24}
}
func (m *ConfigListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigListQuery.Unmarshal(m, b)
}
func (m *ConfigListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigListQuery.Marshal(b, m, deterministic)
}
func (dst *ConfigListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigListQuery.Merge(dst, src)
}
func (m *ConfigListQuery) XXX_Size() int {
	return xxx_messageInfo_ConfigListQuery.Size(m)
}
func (m *ConfigListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigListQuery proto.InternalMessageInfo

type StatsListQuery struct {
	// Type of stats to retrieve.
	Type StatsListQuery_Type `protobuf:"varint,1,opt,name=type,proto3,enum=common.v1.StatsListQuery_Type" json:"type,omitempty"`
	// An optional list of volume (or node or other) ids to query.  Empty list will return all.
	Ids                  []uint32 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsListQuery) Reset()         { *m = StatsListQuery{} }
func (m *StatsListQuery) String() string { return proto.CompactTextString(m) }
func (*StatsListQuery) ProtoMessage()    {}
func (*StatsListQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{25}
}
func (m *StatsListQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsListQuery.Unmarshal(m, b)
}
func (m *StatsListQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsListQuery.Marshal(b, m, deterministic)
}
func (dst *StatsListQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsListQuery.Merge(dst, src)
}
func (m *StatsListQuery) XXX_Size() int {
	return xxx_messageInfo_StatsListQuery.Size(m)
}
func (m *StatsListQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsListQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StatsListQuery proto.InternalMessageInfo

func (m *StatsListQuery) GetType() StatsListQuery_Type {
	if m != nil {
		return m.Type
	}
	return StatsListQuery_VOLUME
}

func (m *StatsListQuery) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Counter struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{26}
}
func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (dst *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(dst, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Gauge struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gauge) Reset()         { *m = Gauge{} }
func (m *Gauge) String() string { return proto.CompactTextString(m) }
func (*Gauge) ProtoMessage()    {}
func (*Gauge) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{27}
}
func (m *Gauge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gauge.Unmarshal(m, b)
}
func (m *Gauge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gauge.Marshal(b, m, deterministic)
}
func (dst *Gauge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gauge.Merge(dst, src)
}
func (m *Gauge) XXX_Size() int {
	return xxx_messageInfo_Gauge.Size(m)
}
func (m *Gauge) XXX_DiscardUnknown() {
	xxx_messageInfo_Gauge.DiscardUnknown(m)
}

var xxx_messageInfo_Gauge proto.InternalMessageInfo

func (m *Gauge) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Statistic struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to MetricType:
	//	*Statistic_Counter
	//	*Statistic_Gauge
	MetricType           isStatistic_MetricType `protobuf_oneof:"metric_type"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Statistic) Reset()         { *m = Statistic{} }
func (m *Statistic) String() string { return proto.CompactTextString(m) }
func (*Statistic) ProtoMessage()    {}
func (*Statistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{28}
}
func (m *Statistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistic.Unmarshal(m, b)
}
func (m *Statistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistic.Marshal(b, m, deterministic)
}
func (dst *Statistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistic.Merge(dst, src)
}
func (m *Statistic) XXX_Size() int {
	return xxx_messageInfo_Statistic.Size(m)
}
func (m *Statistic) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistic.DiscardUnknown(m)
}

var xxx_messageInfo_Statistic proto.InternalMessageInfo

func (m *Statistic) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Statistic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isStatistic_MetricType interface {
	isStatistic_MetricType()
}

type Statistic_Counter struct {
	Counter *Counter `protobuf:"bytes,3,opt,name=counter,proto3,oneof"`
}

type Statistic_Gauge struct {
	Gauge *Gauge `protobuf:"bytes,4,opt,name=gauge,proto3,oneof"`
}

func (*Statistic_Counter) isStatistic_MetricType() {}

func (*Statistic_Gauge) isStatistic_MetricType() {}

func (m *Statistic) GetMetricType() isStatistic_MetricType {
	if m != nil {
		return m.MetricType
	}
	return nil
}

func (m *Statistic) GetCounter() *Counter {
	if x, ok := m.GetMetricType().(*Statistic_Counter); ok {
		return x.Counter
	}
	return nil
}

func (m *Statistic) GetGauge() *Gauge {
	if x, ok := m.GetMetricType().(*Statistic_Gauge); ok {
		return x.Gauge
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Statistic) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Statistic_OneofMarshaler, _Statistic_OneofUnmarshaler, _Statistic_OneofSizer, []interface{}{
		(*Statistic_Counter)(nil),
		(*Statistic_Gauge)(nil),
	}
}

func _Statistic_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Statistic)
	// metric_type
	switch x := m.MetricType.(type) {
	case *Statistic_Counter:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Counter); err != nil {
			return err
		}
	case *Statistic_Gauge:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Gauge); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Statistic.MetricType has unexpected type %T", x)
	}
	return nil
}

func _Statistic_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Statistic)
	switch tag {
	case 3: // metric_type.counter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Counter)
		err := b.DecodeMessage(msg)
		m.MetricType = &Statistic_Counter{msg}
		return true, err
	case 4: // metric_type.gauge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Gauge)
		err := b.DecodeMessage(msg)
		m.MetricType = &Statistic_Gauge{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Statistic_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Statistic)
	// metric_type
	switch x := m.MetricType.(type) {
	case *Statistic_Counter:
		s := proto.Size(x.Counter)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Statistic_Gauge:
		s := proto.Size(x.Gauge)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StatsListResponse struct {
	Stats                []*Statistic `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StatsListResponse) Reset()         { *m = StatsListResponse{} }
func (m *StatsListResponse) String() string { return proto.CompactTextString(m) }
func (*StatsListResponse) ProtoMessage()    {}
func (*StatsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_18d1b61b60eb90b1, []int{29}
}
func (m *StatsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsListResponse.Unmarshal(m, b)
}
func (m *StatsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsListResponse.Marshal(b, m, deterministic)
}
func (dst *StatsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsListResponse.Merge(dst, src)
}
func (m *StatsListResponse) XXX_Size() int {
	return xxx_messageInfo_StatsListResponse.Size(m)
}
func (m *StatsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsListResponse proto.InternalMessageInfo

func (m *StatsListResponse) GetStats() []*Statistic {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*RpcResult)(nil), "common.v1.RpcResult")
	proto.RegisterType((*DataplaneCommon)(nil), "common.v1.DataplaneCommon")
	proto.RegisterType((*Aes256Key)(nil), "common.v1.Aes256Key")
	proto.RegisterType((*Aes256IV)(nil), "common.v1.Aes256IV")
	proto.RegisterType((*XtsAes256Key)(nil), "common.v1.XtsAes256Key")
	proto.RegisterType((*EncryptedXtsAesKey)(nil), "common.v1.EncryptedXtsAesKey")
	proto.RegisterType((*XtsKeyHMAC)(nil), "common.v1.XtsKeyHMAC")
	proto.RegisterType((*VolumeKeySet)(nil), "common.v1.VolumeKeySet")
	proto.RegisterType((*VolumeCrypto)(nil), "common.v1.VolumeCrypto")
	proto.RegisterType((*DaemonStatus)(nil), "common.v1.DaemonStatus")
	proto.RegisterType((*ConfigUpdateReply)(nil), "common.v1.ConfigUpdateReply")
	proto.RegisterType((*ConfigBool)(nil), "common.v1.ConfigBool")
	proto.RegisterType((*ConfigGetBoolReply)(nil), "common.v1.ConfigGetBoolReply")
	proto.RegisterType((*ConfigBoolList)(nil), "common.v1.ConfigBoolList")
	proto.RegisterType((*ConfigUint32)(nil), "common.v1.ConfigUint32")
	proto.RegisterType((*ConfigGetUint32Reply)(nil), "common.v1.ConfigGetUint32Reply")
	proto.RegisterType((*ConfigUint32List)(nil), "common.v1.ConfigUint32List")
	proto.RegisterType((*ConfigUint64)(nil), "common.v1.ConfigUint64")
	proto.RegisterType((*ConfigGetUint64Reply)(nil), "common.v1.ConfigGetUint64Reply")
	proto.RegisterType((*ConfigUint64List)(nil), "common.v1.ConfigUint64List")
	proto.RegisterType((*ConfigString)(nil), "common.v1.ConfigString")
	proto.RegisterType((*ConfigGetStringReply)(nil), "common.v1.ConfigGetStringReply")
	proto.RegisterType((*ConfigStringList)(nil), "common.v1.ConfigStringList")
	proto.RegisterType((*ConfigKey)(nil), "common.v1.ConfigKey")
	proto.RegisterType((*ConfigListQuery)(nil), "common.v1.ConfigListQuery")
	proto.RegisterType((*StatsListQuery)(nil), "common.v1.StatsListQuery")
	proto.RegisterType((*Counter)(nil), "common.v1.Counter")
	proto.RegisterType((*Gauge)(nil), "common.v1.Gauge")
	proto.RegisterType((*Statistic)(nil), "common.v1.Statistic")
	proto.RegisterType((*StatsListResponse)(nil), "common.v1.StatsListResponse")
	proto.RegisterEnum("common.v1.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("common.v1.ConfigGetStatus", ConfigGetStatus_name, ConfigGetStatus_value)
	proto.RegisterEnum("common.v1.ConfigUpdateStatus", ConfigUpdateStatus_name, ConfigUpdateStatus_value)
	proto.RegisterEnum("common.v1.VolumeCrypto_VolumeCryptoState", VolumeCrypto_VolumeCryptoState_name, VolumeCrypto_VolumeCryptoState_value)
	proto.RegisterEnum("common.v1.DaemonStatus_ProgramState", DaemonStatus_ProgramState_name, DaemonStatus_ProgramState_value)
	proto.RegisterEnum("common.v1.StatsListQuery_Type", StatsListQuery_Type_name, StatsListQuery_Type_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_18d1b61b60eb90b1) }

var fileDescriptor_common_18d1b61b60eb90b1 = []byte{
	// 1278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x5e, 0xe7, 0xaf, 0xcd, 0x69, 0x92, 0xba, 0xd3, 0x96, 0x46, 0xab, 0x2d, 0x44, 0x16, 0x48,
	0xd9, 0x2e, 0xa4, 0x6c, 0xb6, 0x1b, 0x09, 0x24, 0x84, 0x52, 0xdb, 0x6d, 0xa3, 0xa6, 0x71, 0x77,
	0xec, 0x54, 0xdb, 0xbd, 0x89, 0x4c, 0x32, 0x64, 0xad, 0x6d, 0xec, 0xc8, 0x9e, 0x44, 0x84, 0x37,
	0xe0, 0x0e, 0x04, 0x12, 0x70, 0xc9, 0x05, 0xef, 0x02, 0xbc, 0x09, 0xf7, 0x3c, 0x00, 0x9a, 0x1f,
	0x27, 0x4e, 0x7f, 0xe8, 0x5e, 0xa1, 0xbd, 0x9b, 0x73, 0xce, 0x37, 0x67, 0xbe, 0xf3, 0xcd, 0x8c,
	0xe7, 0x18, 0x0a, 0xfd, 0x60, 0x34, 0x0a, 0xfc, 0xda, 0x38, 0x0c, 0x68, 0x80, 0xf2, 0xd2, 0x9a,
	0x3e, 0xd5, 0x5e, 0x43, 0x1e, 0x8f, 0xfb, 0x98, 0x44, 0x93, 0x2b, 0x8a, 0xca, 0xb0, 0x12, 0x4d,
	0xfa, 0x7d, 0x12, 0x45, 0x65, 0xa5, 0xa2, 0x54, 0x57, 0x71, 0x6c, 0xa2, 0xf7, 0x20, 0x17, 0x12,
	0x37, 0x0a, 0xfc, 0x72, 0xaa, 0xa2, 0x54, 0xf3, 0x58, 0x5a, 0xe8, 0x31, 0x64, 0xfa, 0xc1, 0x80,
	0x94, 0xd3, 0x15, 0xa5, 0x5a, 0xaa, 0x6f, 0xd7, 0xe6, 0x89, 0x6b, 0x36, 0x75, 0xe9, 0x24, 0xd2,
	0x83, 0x01, 0xc1, 0x1c, 0xa2, 0xf5, 0x60, 0xdd, 0x70, 0xa9, 0x3b, 0xbe, 0x72, 0x7d, 0xa2, 0x73,
	0x18, 0x42, 0x90, 0x99, 0x4c, 0xbc, 0x01, 0x9f, 0x9d, 0xc7, 0x7c, 0x8c, 0x1e, 0xc2, 0x6a, 0x48,
	0xa6, 0x5e, 0xe4, 0x05, 0x7e, 0x39, 0x53, 0x51, 0xaa, 0x69, 0x3c, 0xb7, 0xd1, 0x23, 0xc8, 0x4f,
	0x49, 0xc8, 0x86, 0x64, 0x50, 0xce, 0x72, 0x86, 0x0b, 0x87, 0xb6, 0x0b, 0xf9, 0x26, 0x89, 0xea,
	0xcf, 0x1b, 0xa7, 0x64, 0x86, 0x54, 0x48, 0xbf, 0x21, 0x33, 0x5e, 0x46, 0x01, 0xb3, 0xa1, 0xf6,
	0x10, 0x56, 0x45, 0xb8, 0x75, 0x81, 0x4a, 0x90, 0xf2, 0xa6, 0x32, 0x98, 0xf2, 0xa6, 0x5a, 0x05,
	0x0a, 0x2f, 0x69, 0xf4, 0x5f, 0xb3, 0xab, 0x80, 0x4c, 0xbf, 0x1f, 0xce, 0xc6, 0x94, 0x0c, 0x04,
	0x94, 0xe1, 0x10, 0x64, 0xc8, 0x02, 0xc8, 0xc7, 0x5a, 0x05, 0xe0, 0x25, 0x65, 0xd1, 0x93, 0xb3,
	0xa6, 0xce, 0x10, 0xaf, 0x47, 0x6e, 0x3f, 0x46, 0xb0, 0xb1, 0xf6, 0x19, 0x14, 0x2e, 0x82, 0xab,
	0xc9, 0x88, 0x9c, 0x92, 0x99, 0x4d, 0x28, 0x7a, 0x0c, 0xe9, 0xe9, 0xe8, 0x0d, 0x87, 0xac, 0xd5,
	0x77, 0x12, 0x1a, 0x26, 0x39, 0x61, 0x86, 0xd1, 0x7e, 0x4e, 0xc5, 0x73, 0x75, 0xc6, 0x25, 0x40,
	0x1f, 0x41, 0x89, 0xb3, 0x0a, 0x7a, 0x52, 0x08, 0xbe, 0x41, 0x45, 0x5c, 0x14, 0xde, 0x0b, 0xe1,
	0x44, 0x6d, 0x28, 0x48, 0x58, 0x44, 0x5d, 0x1a, 0xef, 0xd7, 0xe3, 0xc4, 0x5a, 0xc9, 0xac, 0x4b,
	0x06, 0xdb, 0x48, 0x82, 0xd7, 0xfa, 0x0b, 0x83, 0x2d, 0xfa, 0x86, 0xcc, 0x22, 0x42, 0x7b, 0xe3,
	0x90, 0x44, 0xc4, 0xa7, 0x72, 0x33, 0x8a, 0xc2, 0x7b, 0x2e, 0x9c, 0x68, 0x1f, 0x72, 0xc2, 0xc1,
	0x37, 0x72, 0xb9, 0xb4, 0xa4, 0x00, 0x58, 0xc2, 0xb4, 0xcf, 0x61, 0xe3, 0xc6, 0xca, 0xa8, 0x00,
	0xab, 0x17, 0xba, 0xdd, 0xeb, 0x58, 0x1d, 0x53, 0x7d, 0x80, 0x76, 0x60, 0x93, 0x59, 0x47, 0xdd,
	0x76, 0xfb, 0xb2, 0x67, 0x76, 0x74, 0x7c, 0x79, 0xee, 0x98, 0x86, 0xaa, 0x68, 0xdf, 0xa5, 0xa0,
	0x60, 0xb8, 0x64, 0x14, 0xf8, 0xe2, 0xe4, 0xa1, 0x16, 0x14, 0xc7, 0x61, 0x30, 0x0c, 0xdd, 0x91,
	0xac, 0x59, 0xe1, 0x35, 0x7f, 0x98, 0x20, 0x91, 0xc4, 0xd7, 0xce, 0x05, 0x58, 0x94, 0x5b, 0x18,
	0x27, 0x2c, 0x54, 0x87, 0xed, 0xa5, 0x54, 0xbd, 0x11, 0x89, 0x22, 0x77, 0x48, 0xe4, 0x65, 0xd8,
	0x4c, 0x82, 0xcf, 0x44, 0x48, 0xfb, 0x16, 0x0a, 0xc9, 0x8c, 0x68, 0x0d, 0x56, 0x8c, 0x79, 0x15,
	0xeb, 0xb0, 0x66, 0xd8, 0x3d, 0xdb, 0x69, 0x62, 0xa7, 0xd5, 0x39, 0x56, 0x15, 0x56, 0xa4, 0x61,
	0xf7, 0xb0, 0xd9, 0x34, 0x2e, 0xd5, 0xd4, 0x3c, 0x6c, 0x9d, 0x9f, 0xb3, 0x70, 0x1a, 0x95, 0x00,
	0x62, 0x87, 0x69, 0xa8, 0x19, 0x09, 0x37, 0x31, 0xb6, 0xb0, 0x9a, 0x95, 0x70, 0x1d, 0xb7, 0x9c,
	0x96, 0xde, 0x6c, 0xab, 0x39, 0xed, 0x1b, 0xd8, 0xd0, 0x03, 0xff, 0x6b, 0x6f, 0xd8, 0x1d, 0x0f,
	0x58, 0x35, 0x64, 0x7c, 0x35, 0x43, 0xcf, 0x21, 0x17, 0xf1, 0x4a, 0xa5, 0x10, 0xbb, 0x09, 0x21,
	0x92, 0x68, 0x21, 0x07, 0x96, 0x60, 0xf4, 0x31, 0xbb, 0xf9, 0xec, 0xeb, 0xc0, 0x8b, 0x5d, 0xab,
	0x6f, 0x25, 0xa6, 0xcd, 0xbf, 0x1c, 0x58, 0x62, 0xb4, 0x03, 0x00, 0x91, 0xeb, 0x30, 0x08, 0xae,
	0x92, 0xd7, 0x28, 0xcf, 0xaf, 0x11, 0xda, 0x82, 0xec, 0xd4, 0xbd, 0x9a, 0x08, 0xe5, 0x56, 0xb1,
	0x30, 0xb4, 0xdf, 0x14, 0x40, 0x62, 0xda, 0x31, 0xa1, 0x6c, 0xa6, 0x60, 0x5c, 0xbf, 0xc6, 0xf8,
	0xe1, 0x0d, 0xc6, 0xc7, 0x84, 0xde, 0x49, 0x37, 0x7d, 0x3f, 0x5d, 0xf6, 0xf9, 0xf2, 0x28, 0x19,
	0xc9, 0xd2, 0xb6, 0x6f, 0xe4, 0xe7, 0x5c, 0x38, 0x44, 0xfb, 0x02, 0x4a, 0x0b, 0x5f, 0xdb, 0x8b,
	0x28, 0x7a, 0x02, 0x59, 0x16, 0x61, 0xec, 0xd2, 0x77, 0xcf, 0x16, 0x18, 0xad, 0x01, 0x05, 0x29,
	0xb2, 0xe7, 0xd3, 0x67, 0xf5, 0xfb, 0xa4, 0x29, 0xc6, 0xd2, 0xfc, 0xae, 0xc0, 0xd6, 0xbc, 0x56,
	0x31, 0xf7, 0xff, 0x12, 0xe7, 0xc9, 0x92, 0x38, 0x3b, 0x37, 0x8f, 0x8b, 0x60, 0x23, 0xe4, 0x69,
	0x82, 0x9a, 0xf4, 0x72, 0x81, 0x3e, 0x59, 0x16, 0xe8, 0xce, 0x0c, 0xb7, 0x49, 0xd4, 0x38, 0xb8,
	0x4f, 0xa2, 0xcc, 0x9d, 0x12, 0x35, 0x0e, 0xde, 0x25, 0x89, 0x1a, 0x07, 0xb7, 0x49, 0xd4, 0x38,
	0x78, 0x7b, 0x89, 0x1a, 0x07, 0x37, 0x24, 0xb2, 0x69, 0xe8, 0xf9, 0xc3, 0xfb, 0x24, 0xca, 0xdf,
	0x2a, 0x91, 0x98, 0xfb, 0xae, 0x48, 0x24, 0xd9, 0x5c, 0x93, 0x48, 0x78, 0xdf, 0x4e, 0x22, 0x99,
	0x41, 0x4a, 0xb4, 0x0b, 0x79, 0xe1, 0xbe, 0xf6, 0x8e, 0x0b, 0x7d, 0xb4, 0x0d, 0x58, 0x17, 0x61,
	0x96, 0xfb, 0xc5, 0x84, 0x84, 0x33, 0x8d, 0x42, 0x89, 0x55, 0x18, 0xcd, 0x3d, 0xa8, 0x0e, 0x19,
	0x3a, 0x1b, 0xc7, 0x2f, 0xc6, 0xfb, 0xd7, 0xba, 0x9a, 0x05, 0xb0, 0xe6, 0xcc, 0xc6, 0x04, 0x73,
	0x2c, 0x5b, 0xca, 0x1b, 0x44, 0xe5, 0x54, 0x25, 0x5d, 0x2d, 0x62, 0x36, 0xd4, 0x1e, 0x41, 0x86,
	0xc5, 0x11, 0x40, 0xee, 0xc2, 0x6a, 0x77, 0xcf, 0xd8, 0x87, 0x7f, 0x15, 0x32, 0x1d, 0xcb, 0x30,
	0x55, 0x45, 0xfb, 0x00, 0x56, 0xf4, 0x60, 0xe2, 0x53, 0x12, 0x2e, 0xf6, 0x4c, 0x49, 0x1e, 0xeb,
	0x5d, 0xc8, 0x1e, 0xbb, 0x93, 0x21, 0xb9, 0x23, 0xfc, 0x8b, 0x02, 0x79, 0xc6, 0xc6, 0x8b, 0xa8,
	0xd7, 0xe7, 0x0d, 0xcd, 0x80, 0x03, 0x8a, 0x38, 0xe5, 0x0d, 0x58, 0xdb, 0xe1, 0xbb, 0xa3, 0xf8,
	0x14, 0xf0, 0x31, 0xaa, 0xc1, 0x4a, 0x5f, 0xac, 0x28, 0x37, 0x0e, 0x2d, 0x49, 0xc9, 0x23, 0x27,
	0x0f, 0x70, 0x0c, 0x42, 0x55, 0xc8, 0x0e, 0x19, 0x01, 0xf9, 0x7a, 0xab, 0x09, 0x34, 0x27, 0x76,
	0xf2, 0x00, 0x0b, 0xc0, 0x61, 0x11, 0xd6, 0x46, 0x84, 0x86, 0x5e, 0xbf, 0xc7, 0xa4, 0xd0, 0xbe,
	0x84, 0x8d, 0xb9, 0x4e, 0x98, 0x44, 0xe3, 0xc0, 0x8f, 0x08, 0xda, 0x83, 0x2c, 0x3b, 0x3f, 0xf1,
	0x36, 0x6e, 0x5d, 0x13, 0x95, 0x97, 0x81, 0x05, 0x64, 0xef, 0x6f, 0x05, 0x60, 0xd1, 0x3f, 0xb2,
	0xf7, 0xcd, 0x76, 0x9a, 0x4e, 0x77, 0xfe, 0x7c, 0x96, 0x20, 0x2f, 0x1d, 0xd6, 0xa9, 0xfa, 0x87,
	0x82, 0xb6, 0x60, 0x5d, 0xda, 0x4d, 0x5d, 0x37, 0x79, 0x43, 0xf0, 0x97, 0x82, 0x36, 0xa1, 0x24,
	0xbd, 0x3a, 0x36, 0x9b, 0xcc, 0xf9, 0xa7, 0x82, 0x76, 0x00, 0x49, 0xe7, 0x61, 0xd3, 0xe8, 0x61,
	0xf3, 0x45, 0xd7, 0xb4, 0x1d, 0xf5, 0xfb, 0x34, 0x2a, 0xc3, 0xa6, 0x0c, 0x74, 0x3b, 0xcd, 0xae,
	0x73, 0x62, 0xe1, 0xd6, 0x2b, 0xd3, 0x50, 0x7f, 0x48, 0xa3, 0x6d, 0x50, 0x65, 0xe4, 0xc8, 0xc2,
	0x87, 0x2d, 0xc3, 0x30, 0x3b, 0xea, 0x8f, 0x49, 0x77, 0xc7, 0x72, 0x7a, 0x47, 0x56, 0xb7, 0x63,
	0xa8, 0x3f, 0xa5, 0x13, 0x5c, 0x74, 0xab, 0x73, 0xd4, 0x6e, 0xe9, 0x8e, 0xfa, 0x6b, 0x32, 0xbb,
	0x6d, 0xe2, 0x0b, 0x13, 0xcb, 0xb7, 0xfb, 0x9f, 0xf4, 0x5e, 0x3b, 0x3e, 0x90, 0xf3, 0x8b, 0xc6,
	0x5e, 0xf7, 0x63, 0xd3, 0x89, 0x8b, 0x05, 0xc8, 0x31, 0xcb, 0x3a, 0x55, 0x15, 0xa6, 0x04, 0x1b,
	0x9f, 0xb5, 0x6c, 0x9b, 0x35, 0x06, 0x29, 0xd6, 0x18, 0x30, 0xc7, 0x51, 0xb3, 0xd5, 0x36, 0x0d,
	0x35, 0xbd, 0x37, 0x88, 0x1f, 0xd2, 0xe4, 0x5b, 0xce, 0x12, 0xda, 0x4b, 0x09, 0xed, 0x38, 0xe1,
	0x06, 0x14, 0xd9, 0xb8, 0x75, 0x76, 0xd6, 0x75, 0x9a, 0x87, 0x6d, 0x53, 0xa4, 0xb4, 0x13, 0x29,
	0x63, 0x08, 0xeb, 0x4d, 0x7a, 0x56, 0xa7, 0x7d, 0xa9, 0x66, 0x0e, 0x3f, 0x7d, 0x55, 0x63, 0x2d,
	0x7d, 0x2d, 0xa2, 0x41, 0xe8, 0x0e, 0x49, 0x10, 0xd5, 0x7c, 0x42, 0xf7, 0xe7, 0xd6, 0x7e, 0x44,
	0xc2, 0xa9, 0xd7, 0x27, 0xfb, 0x62, 0x8b, 0xf7, 0xa7, 0x4f, 0xbf, 0xca, 0xf1, 0x1f, 0x8f, 0x67,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x57, 0x08, 0xdb, 0xbc, 0x88, 0x0c, 0x00, 0x00,
}
