# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: director.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='director.proto',
  package='storageos_rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64irector.proto\x12\rstorageos_rpc\x1a\x0c\x63ommon.proto\"\x19\n\x17\x44irectorVolumeListQuery\"\xbf\x02\n\x0e\x44irectorVolume\x12\x11\n\tvolume_id\x18\x01 \x01(\r\x12\x12\n\nwrite_pipe\x18\x02 \x01(\r\x12\x11\n\tread_pipe\x18\x03 \x01(\r\x12\x39\n\x06labels\x18\x04 \x03(\x0b\x32).storageos_rpc.DirectorVolume.LabelsEntry\x12\x0b\n\x03qos\x18\x05 \x01(\x04\x12\x12\n\nreplica_id\x18\x06 \x03(\r\x12\x39\n\x06status\x18\x07 \x03(\x0b\x32).storageos_rpc.DirectorVolume.StatusEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bStatusEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1b\n\x19\x44irectorRedirectListQuery\"8\n\x10\x44irectorRedirect\x12\x11\n\tsource_id\x18\x01 \x01(\r\x12\x11\n\ttarget_id\x18\x02 \x01(\r2\x8c\x04\n\x0e\x44irectorConfig\x12L\n\x0fVolumeConfigure\x12\x1d.storageos_rpc.DirectorVolume\x1a\x18.storageos_rpc.RpcResult\"\x00\x12N\n\x11VolumeUnconfigure\x12\x1d.storageos_rpc.DirectorVolume\x1a\x18.storageos_rpc.RpcResult\"\x00\x12W\n\nVolumeList\x12&.storageos_rpc.DirectorVolumeListQuery\x1a\x1d.storageos_rpc.DirectorVolume\"\x00\x30\x01\x12P\n\x11RedirectConfigure\x12\x1f.storageos_rpc.DirectorRedirect\x1a\x18.storageos_rpc.RpcResult\"\x00\x12R\n\x13RedirectUnconfigure\x12\x1f.storageos_rpc.DirectorRedirect\x1a\x18.storageos_rpc.RpcResult\"\x00\x12]\n\x0cRedirectList\x12(.storageos_rpc.DirectorRedirectListQuery\x1a\x1f.storageos_rpc.DirectorRedirect\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_DIRECTORVOLUMELISTQUERY = _descriptor.Descriptor(
  name='DirectorVolumeListQuery',
  full_name='storageos_rpc.DirectorVolumeListQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=72,
)


_DIRECTORVOLUME_LABELSENTRY = _descriptor.Descriptor(
  name='LabelsEntry',
  full_name='storageos_rpc.DirectorVolume.LabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='storageos_rpc.DirectorVolume.LabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='storageos_rpc.DirectorVolume.LabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=347,
)

_DIRECTORVOLUME_STATUSENTRY = _descriptor.Descriptor(
  name='StatusEntry',
  full_name='storageos_rpc.DirectorVolume.StatusEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='storageos_rpc.DirectorVolume.StatusEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='storageos_rpc.DirectorVolume.StatusEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=394,
)

_DIRECTORVOLUME = _descriptor.Descriptor(
  name='DirectorVolume',
  full_name='storageos_rpc.DirectorVolume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume_id', full_name='storageos_rpc.DirectorVolume.volume_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='write_pipe', full_name='storageos_rpc.DirectorVolume.write_pipe', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_pipe', full_name='storageos_rpc.DirectorVolume.read_pipe', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labels', full_name='storageos_rpc.DirectorVolume.labels', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qos', full_name='storageos_rpc.DirectorVolume.qos', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replica_id', full_name='storageos_rpc.DirectorVolume.replica_id', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='storageos_rpc.DirectorVolume.status', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DIRECTORVOLUME_LABELSENTRY, _DIRECTORVOLUME_STATUSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=394,
)


_DIRECTORREDIRECTLISTQUERY = _descriptor.Descriptor(
  name='DirectorRedirectListQuery',
  full_name='storageos_rpc.DirectorRedirectListQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=423,
)


_DIRECTORREDIRECT = _descriptor.Descriptor(
  name='DirectorRedirect',
  full_name='storageos_rpc.DirectorRedirect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_id', full_name='storageos_rpc.DirectorRedirect.source_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_id', full_name='storageos_rpc.DirectorRedirect.target_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=481,
)

_DIRECTORVOLUME_LABELSENTRY.containing_type = _DIRECTORVOLUME
_DIRECTORVOLUME_STATUSENTRY.containing_type = _DIRECTORVOLUME
_DIRECTORVOLUME.fields_by_name['labels'].message_type = _DIRECTORVOLUME_LABELSENTRY
_DIRECTORVOLUME.fields_by_name['status'].message_type = _DIRECTORVOLUME_STATUSENTRY
DESCRIPTOR.message_types_by_name['DirectorVolumeListQuery'] = _DIRECTORVOLUMELISTQUERY
DESCRIPTOR.message_types_by_name['DirectorVolume'] = _DIRECTORVOLUME
DESCRIPTOR.message_types_by_name['DirectorRedirectListQuery'] = _DIRECTORREDIRECTLISTQUERY
DESCRIPTOR.message_types_by_name['DirectorRedirect'] = _DIRECTORREDIRECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DirectorVolumeListQuery = _reflection.GeneratedProtocolMessageType('DirectorVolumeListQuery', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTORVOLUMELISTQUERY,
  __module__ = 'director_pb2'
  # @@protoc_insertion_point(class_scope:storageos_rpc.DirectorVolumeListQuery)
  ))
_sym_db.RegisterMessage(DirectorVolumeListQuery)

DirectorVolume = _reflection.GeneratedProtocolMessageType('DirectorVolume', (_message.Message,), dict(

  LabelsEntry = _reflection.GeneratedProtocolMessageType('LabelsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DIRECTORVOLUME_LABELSENTRY,
    __module__ = 'director_pb2'
    # @@protoc_insertion_point(class_scope:storageos_rpc.DirectorVolume.LabelsEntry)
    ))
  ,

  StatusEntry = _reflection.GeneratedProtocolMessageType('StatusEntry', (_message.Message,), dict(
    DESCRIPTOR = _DIRECTORVOLUME_STATUSENTRY,
    __module__ = 'director_pb2'
    # @@protoc_insertion_point(class_scope:storageos_rpc.DirectorVolume.StatusEntry)
    ))
  ,
  DESCRIPTOR = _DIRECTORVOLUME,
  __module__ = 'director_pb2'
  # @@protoc_insertion_point(class_scope:storageos_rpc.DirectorVolume)
  ))
_sym_db.RegisterMessage(DirectorVolume)
_sym_db.RegisterMessage(DirectorVolume.LabelsEntry)
_sym_db.RegisterMessage(DirectorVolume.StatusEntry)

DirectorRedirectListQuery = _reflection.GeneratedProtocolMessageType('DirectorRedirectListQuery', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTORREDIRECTLISTQUERY,
  __module__ = 'director_pb2'
  # @@protoc_insertion_point(class_scope:storageos_rpc.DirectorRedirectListQuery)
  ))
_sym_db.RegisterMessage(DirectorRedirectListQuery)

DirectorRedirect = _reflection.GeneratedProtocolMessageType('DirectorRedirect', (_message.Message,), dict(
  DESCRIPTOR = _DIRECTORREDIRECT,
  __module__ = 'director_pb2'
  # @@protoc_insertion_point(class_scope:storageos_rpc.DirectorRedirect)
  ))
_sym_db.RegisterMessage(DirectorRedirect)


_DIRECTORVOLUME_LABELSENTRY.has_options = True
_DIRECTORVOLUME_LABELSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DIRECTORVOLUME_STATUSENTRY.has_options = True
_DIRECTORVOLUME_STATUSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_DIRECTORCONFIG = _descriptor.ServiceDescriptor(
  name='DirectorConfig',
  full_name='storageos_rpc.DirectorConfig',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=484,
  serialized_end=1008,
  methods=[
  _descriptor.MethodDescriptor(
    name='VolumeConfigure',
    full_name='storageos_rpc.DirectorConfig.VolumeConfigure',
    index=0,
    containing_service=None,
    input_type=_DIRECTORVOLUME,
    output_type=common__pb2._RPCRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VolumeUnconfigure',
    full_name='storageos_rpc.DirectorConfig.VolumeUnconfigure',
    index=1,
    containing_service=None,
    input_type=_DIRECTORVOLUME,
    output_type=common__pb2._RPCRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VolumeList',
    full_name='storageos_rpc.DirectorConfig.VolumeList',
    index=2,
    containing_service=None,
    input_type=_DIRECTORVOLUMELISTQUERY,
    output_type=_DIRECTORVOLUME,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RedirectConfigure',
    full_name='storageos_rpc.DirectorConfig.RedirectConfigure',
    index=3,
    containing_service=None,
    input_type=_DIRECTORREDIRECT,
    output_type=common__pb2._RPCRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RedirectUnconfigure',
    full_name='storageos_rpc.DirectorConfig.RedirectUnconfigure',
    index=4,
    containing_service=None,
    input_type=_DIRECTORREDIRECT,
    output_type=common__pb2._RPCRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RedirectList',
    full_name='storageos_rpc.DirectorConfig.RedirectList',
    index=5,
    containing_service=None,
    input_type=_DIRECTORREDIRECTLISTQUERY,
    output_type=_DIRECTORREDIRECT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DIRECTORCONFIG)

DESCRIPTOR.services_by_name['DirectorConfig'] = _DIRECTORCONFIG

# @@protoc_insertion_point(module_scope)
