// Code generated by protoc-gen-go. DO NOT EDIT.
// source: director.proto

/*
Package director_v1 is a generated protocol buffer package.

It is generated from these files:
	director.proto

It has these top-level messages:
	DirectorStatusRequest
	DirectorStatus
	DirectorVolumeListQuery
	DirectorVolumeStatistics
	DirectorVolumeStatus
	DirectorVolume
	DirectorVolumeList
	DirectorPresentationListQuery
	DirectorPresentation
	DirectorPresentationList
*/
package director_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common_v1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DirectorStatusRequest struct {
}

func (m *DirectorStatusRequest) Reset()                    { *m = DirectorStatusRequest{} }
func (m *DirectorStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*DirectorStatusRequest) ProtoMessage()               {}
func (*DirectorStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DirectorStatus struct {
	// The version control info string.
	VersionInfo string `protobuf:"bytes,1,opt,name=version_info,json=versionInfo" json:"version_info,omitempty"`
}

func (m *DirectorStatus) Reset()                    { *m = DirectorStatus{} }
func (m *DirectorStatus) String() string            { return proto.CompactTextString(m) }
func (*DirectorStatus) ProtoMessage()               {}
func (*DirectorStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DirectorStatus) GetVersionInfo() string {
	if m != nil {
		return m.VersionInfo
	}
	return ""
}

type DirectorVolumeListQuery struct {
	// A possibly-empty list of volume IDs to query.
	VolumeIds []uint32 `protobuf:"varint,1,rep,packed,name=volume_ids,json=volumeIds" json:"volume_ids,omitempty"`
}

func (m *DirectorVolumeListQuery) Reset()                    { *m = DirectorVolumeListQuery{} }
func (m *DirectorVolumeListQuery) String() string            { return proto.CompactTextString(m) }
func (*DirectorVolumeListQuery) ProtoMessage()               {}
func (*DirectorVolumeListQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DirectorVolumeListQuery) GetVolumeIds() []uint32 {
	if m != nil {
		return m.VolumeIds
	}
	return nil
}

type DirectorVolumeStatistics struct {
}

func (m *DirectorVolumeStatistics) Reset()                    { *m = DirectorVolumeStatistics{} }
func (m *DirectorVolumeStatistics) String() string            { return proto.CompactTextString(m) }
func (*DirectorVolumeStatistics) ProtoMessage()               {}
func (*DirectorVolumeStatistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DirectorVolumeStatus struct {
}

func (m *DirectorVolumeStatus) Reset()                    { *m = DirectorVolumeStatus{} }
func (m *DirectorVolumeStatus) String() string            { return proto.CompactTextString(m) }
func (*DirectorVolumeStatus) ProtoMessage()               {}
func (*DirectorVolumeStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// *
// Volume message for Director RPCs.
//
// Note this does should not be used to configure Presentation inodes, volumes that point
// at other volumes. Use DirectorPresentation for that.
type DirectorVolume struct {
	Cc *common_v1.DataplaneCommon `protobuf:"bytes,1,opt,name=cc" json:"cc,omitempty"`
	// The volume ID.
	VolumeId uint32 `protobuf:"varint,2,opt,name=volume_id,json=volumeId" json:"volume_id,omitempty"`
	// The write_pipe (identifies the plugin).
	WritePipe uint32 `protobuf:"varint,3,opt,name=write_pipe,json=writePipe" json:"write_pipe,omitempty"`
	// The read pipe (should be write_pipe + 1 in all current plugins).
	ReadPipe uint32 `protobuf:"varint,4,opt,name=read_pipe,json=readPipe" json:"read_pipe,omitempty"`
	// Quality of service indicator.
	Qos uint64 `protobuf:"varint,5,opt,name=qos" json:"qos,omitempty"`
	// List of replica inodes.
	ReplicaIds []uint32 `protobuf:"varint,6,rep,packed,name=replica_ids,json=replicaIds" json:"replica_ids,omitempty"`
	// Volume statistics.
	Stats *DirectorVolumeStatistics `protobuf:"bytes,7,opt,name=stats" json:"stats,omitempty"`
	// Volume status, e.g. retry condition.
	Status *DirectorVolumeStatus `protobuf:"bytes,8,opt,name=status" json:"status,omitempty"`
}

func (m *DirectorVolume) Reset()                    { *m = DirectorVolume{} }
func (m *DirectorVolume) String() string            { return proto.CompactTextString(m) }
func (*DirectorVolume) ProtoMessage()               {}
func (*DirectorVolume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DirectorVolume) GetCc() *common_v1.DataplaneCommon {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *DirectorVolume) GetVolumeId() uint32 {
	if m != nil {
		return m.VolumeId
	}
	return 0
}

func (m *DirectorVolume) GetWritePipe() uint32 {
	if m != nil {
		return m.WritePipe
	}
	return 0
}

func (m *DirectorVolume) GetReadPipe() uint32 {
	if m != nil {
		return m.ReadPipe
	}
	return 0
}

func (m *DirectorVolume) GetQos() uint64 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func (m *DirectorVolume) GetReplicaIds() []uint32 {
	if m != nil {
		return m.ReplicaIds
	}
	return nil
}

func (m *DirectorVolume) GetStats() *DirectorVolumeStatistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *DirectorVolume) GetStatus() *DirectorVolumeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type DirectorVolumeList struct {
	Volumes []*DirectorVolume `protobuf:"bytes,1,rep,name=volumes" json:"volumes,omitempty"`
}

func (m *DirectorVolumeList) Reset()                    { *m = DirectorVolumeList{} }
func (m *DirectorVolumeList) String() string            { return proto.CompactTextString(m) }
func (*DirectorVolumeList) ProtoMessage()               {}
func (*DirectorVolumeList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DirectorVolumeList) GetVolumes() []*DirectorVolume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type DirectorPresentationListQuery struct {
	// A possibly-empty list of volume IDs to query.
	PresentationId []uint32 `protobuf:"varint,1,rep,packed,name=presentation_id,json=presentationId" json:"presentation_id,omitempty"`
}

func (m *DirectorPresentationListQuery) Reset()                    { *m = DirectorPresentationListQuery{} }
func (m *DirectorPresentationListQuery) String() string            { return proto.CompactTextString(m) }
func (*DirectorPresentationListQuery) ProtoMessage()               {}
func (*DirectorPresentationListQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DirectorPresentationListQuery) GetPresentationId() []uint32 {
	if m != nil {
		return m.PresentationId
	}
	return nil
}

// *
// Presentation volume message for Director RPCs.
//
// The minimum amount of information required to specify the 'presentation' or source volume,
// the volume that is presented to the user and (usually) mounted. All actual work
// is done on the target volume, which has actual storage associated with it.
type DirectorPresentation struct {
	Cc *common_v1.DataplaneCommon `protobuf:"bytes,1,opt,name=cc" json:"cc,omitempty"`
	// The inode the user mounts or opens.
	SourceId uint32 `protobuf:"varint,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	// The underlying inode of the StorageOS volume.
	TargetId uint32 `protobuf:"varint,3,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
}

func (m *DirectorPresentation) Reset()                    { *m = DirectorPresentation{} }
func (m *DirectorPresentation) String() string            { return proto.CompactTextString(m) }
func (*DirectorPresentation) ProtoMessage()               {}
func (*DirectorPresentation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DirectorPresentation) GetCc() *common_v1.DataplaneCommon {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *DirectorPresentation) GetSourceId() uint32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *DirectorPresentation) GetTargetId() uint32 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

type DirectorPresentationList struct {
	Presentations []*DirectorPresentation `protobuf:"bytes,1,rep,name=presentations" json:"presentations,omitempty"`
}

func (m *DirectorPresentationList) Reset()                    { *m = DirectorPresentationList{} }
func (m *DirectorPresentationList) String() string            { return proto.CompactTextString(m) }
func (*DirectorPresentationList) ProtoMessage()               {}
func (*DirectorPresentationList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DirectorPresentationList) GetPresentations() []*DirectorPresentation {
	if m != nil {
		return m.Presentations
	}
	return nil
}

func init() {
	proto.RegisterType((*DirectorStatusRequest)(nil), "director.v1.DirectorStatusRequest")
	proto.RegisterType((*DirectorStatus)(nil), "director.v1.DirectorStatus")
	proto.RegisterType((*DirectorVolumeListQuery)(nil), "director.v1.DirectorVolumeListQuery")
	proto.RegisterType((*DirectorVolumeStatistics)(nil), "director.v1.DirectorVolumeStatistics")
	proto.RegisterType((*DirectorVolumeStatus)(nil), "director.v1.DirectorVolumeStatus")
	proto.RegisterType((*DirectorVolume)(nil), "director.v1.DirectorVolume")
	proto.RegisterType((*DirectorVolumeList)(nil), "director.v1.DirectorVolumeList")
	proto.RegisterType((*DirectorPresentationListQuery)(nil), "director.v1.DirectorPresentationListQuery")
	proto.RegisterType((*DirectorPresentation)(nil), "director.v1.DirectorPresentation")
	proto.RegisterType((*DirectorPresentationList)(nil), "director.v1.DirectorPresentationList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Director service

type DirectorClient interface {
	// *
	// Get program status.
	Status(ctx context.Context, in *DirectorStatusRequest, opts ...grpc.CallOption) (*DirectorStatus, error)
	// *
	// Add configuration for the given DirectorVolume message.
	//
	// @return  RpcResult
	VolumeCreate(ctx context.Context, in *DirectorVolume, opts ...grpc.CallOption) (*common_v1.RpcResult, error)
	// *
	// Update configuration for the given DirectorVolume message.
	//
	// @return  RpcResult
	VolumeUpdate(ctx context.Context, in *DirectorVolume, opts ...grpc.CallOption) (*common_v1.RpcResult, error)
	// *
	// Remove configuration for the given DirectorVolume message.
	//
	// returns RpcResult
	VolumeDelete(ctx context.Context, in *DirectorVolume, opts ...grpc.CallOption) (*common_v1.RpcResult, error)
	// *
	// List configured volumes, optionally filtered using a DirectorVolumeListQuery
	// message.
	//
	// returns  A DirectorVolumeList message containing DirectorVolume objects,
	//          if any are found matching the filter
	VolumeList(ctx context.Context, in *DirectorVolumeListQuery, opts ...grpc.CallOption) (*DirectorVolumeList, error)
	// *
	// Add configuration for a Presentation volume specified in the DirectorPresentation message.
	//
	// returns RpcResult
	PresentationCreate(ctx context.Context, in *DirectorPresentation, opts ...grpc.CallOption) (*common_v1.RpcResult, error)
	// *
	// Update configuration for a Presentation volume specified in the DirectorPresentation message.
	//
	// returns RpcResult
	PresentationUpdate(ctx context.Context, in *DirectorPresentation, opts ...grpc.CallOption) (*common_v1.RpcResult, error)
	// *
	// Remove configuration for the Presentation volume specified in the DirectorPresentation message.
	//
	// returns RpcResult
	PresentationDelete(ctx context.Context, in *DirectorPresentation, opts ...grpc.CallOption) (*common_v1.RpcResult, error)
	// *
	// List configured Presentation volumes, optionally filtered using a DirectorPresentationListQuery
	// message.
	//
	// returns A DirectorPresentationList message containing DirectorPresentation mesages,
	//         if any are found matching the filter.
	PresentationList(ctx context.Context, in *DirectorPresentationListQuery, opts ...grpc.CallOption) (*DirectorPresentationList, error)
}

type directorClient struct {
	cc *grpc.ClientConn
}

func NewDirectorClient(cc *grpc.ClientConn) DirectorClient {
	return &directorClient{cc}
}

func (c *directorClient) Status(ctx context.Context, in *DirectorStatusRequest, opts ...grpc.CallOption) (*DirectorStatus, error) {
	out := new(DirectorStatus)
	err := grpc.Invoke(ctx, "/director.v1.Director/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) VolumeCreate(ctx context.Context, in *DirectorVolume, opts ...grpc.CallOption) (*common_v1.RpcResult, error) {
	out := new(common_v1.RpcResult)
	err := grpc.Invoke(ctx, "/director.v1.Director/VolumeCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) VolumeUpdate(ctx context.Context, in *DirectorVolume, opts ...grpc.CallOption) (*common_v1.RpcResult, error) {
	out := new(common_v1.RpcResult)
	err := grpc.Invoke(ctx, "/director.v1.Director/VolumeUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) VolumeDelete(ctx context.Context, in *DirectorVolume, opts ...grpc.CallOption) (*common_v1.RpcResult, error) {
	out := new(common_v1.RpcResult)
	err := grpc.Invoke(ctx, "/director.v1.Director/VolumeDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) VolumeList(ctx context.Context, in *DirectorVolumeListQuery, opts ...grpc.CallOption) (*DirectorVolumeList, error) {
	out := new(DirectorVolumeList)
	err := grpc.Invoke(ctx, "/director.v1.Director/VolumeList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) PresentationCreate(ctx context.Context, in *DirectorPresentation, opts ...grpc.CallOption) (*common_v1.RpcResult, error) {
	out := new(common_v1.RpcResult)
	err := grpc.Invoke(ctx, "/director.v1.Director/PresentationCreate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) PresentationUpdate(ctx context.Context, in *DirectorPresentation, opts ...grpc.CallOption) (*common_v1.RpcResult, error) {
	out := new(common_v1.RpcResult)
	err := grpc.Invoke(ctx, "/director.v1.Director/PresentationUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) PresentationDelete(ctx context.Context, in *DirectorPresentation, opts ...grpc.CallOption) (*common_v1.RpcResult, error) {
	out := new(common_v1.RpcResult)
	err := grpc.Invoke(ctx, "/director.v1.Director/PresentationDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *directorClient) PresentationList(ctx context.Context, in *DirectorPresentationListQuery, opts ...grpc.CallOption) (*DirectorPresentationList, error) {
	out := new(DirectorPresentationList)
	err := grpc.Invoke(ctx, "/director.v1.Director/PresentationList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Director service

type DirectorServer interface {
	// *
	// Get program status.
	Status(context.Context, *DirectorStatusRequest) (*DirectorStatus, error)
	// *
	// Add configuration for the given DirectorVolume message.
	//
	// @return  RpcResult
	VolumeCreate(context.Context, *DirectorVolume) (*common_v1.RpcResult, error)
	// *
	// Update configuration for the given DirectorVolume message.
	//
	// @return  RpcResult
	VolumeUpdate(context.Context, *DirectorVolume) (*common_v1.RpcResult, error)
	// *
	// Remove configuration for the given DirectorVolume message.
	//
	// returns RpcResult
	VolumeDelete(context.Context, *DirectorVolume) (*common_v1.RpcResult, error)
	// *
	// List configured volumes, optionally filtered using a DirectorVolumeListQuery
	// message.
	//
	// returns  A DirectorVolumeList message containing DirectorVolume objects,
	//          if any are found matching the filter
	VolumeList(context.Context, *DirectorVolumeListQuery) (*DirectorVolumeList, error)
	// *
	// Add configuration for a Presentation volume specified in the DirectorPresentation message.
	//
	// returns RpcResult
	PresentationCreate(context.Context, *DirectorPresentation) (*common_v1.RpcResult, error)
	// *
	// Update configuration for a Presentation volume specified in the DirectorPresentation message.
	//
	// returns RpcResult
	PresentationUpdate(context.Context, *DirectorPresentation) (*common_v1.RpcResult, error)
	// *
	// Remove configuration for the Presentation volume specified in the DirectorPresentation message.
	//
	// returns RpcResult
	PresentationDelete(context.Context, *DirectorPresentation) (*common_v1.RpcResult, error)
	// *
	// List configured Presentation volumes, optionally filtered using a DirectorPresentationListQuery
	// message.
	//
	// returns A DirectorPresentationList message containing DirectorPresentation mesages,
	//         if any are found matching the filter.
	PresentationList(context.Context, *DirectorPresentationListQuery) (*DirectorPresentationList, error)
}

func RegisterDirectorServer(s *grpc.Server, srv DirectorServer) {
	s.RegisterService(&_Director_serviceDesc, srv)
}

func _Director_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).Status(ctx, req.(*DirectorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_VolumeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorVolume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).VolumeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/VolumeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).VolumeCreate(ctx, req.(*DirectorVolume))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_VolumeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorVolume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).VolumeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/VolumeUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).VolumeUpdate(ctx, req.(*DirectorVolume))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_VolumeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorVolume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).VolumeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/VolumeDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).VolumeDelete(ctx, req.(*DirectorVolume))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_VolumeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorVolumeListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).VolumeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/VolumeList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).VolumeList(ctx, req.(*DirectorVolumeListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_PresentationCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorPresentation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).PresentationCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/PresentationCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).PresentationCreate(ctx, req.(*DirectorPresentation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_PresentationUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorPresentation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).PresentationUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/PresentationUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).PresentationUpdate(ctx, req.(*DirectorPresentation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_PresentationDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorPresentation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).PresentationDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/PresentationDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).PresentationDelete(ctx, req.(*DirectorPresentation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Director_PresentationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectorPresentationListQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectorServer).PresentationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/director.v1.Director/PresentationList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectorServer).PresentationList(ctx, req.(*DirectorPresentationListQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _Director_serviceDesc = grpc.ServiceDesc{
	ServiceName: "director.v1.Director",
	HandlerType: (*DirectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Director_Status_Handler,
		},
		{
			MethodName: "VolumeCreate",
			Handler:    _Director_VolumeCreate_Handler,
		},
		{
			MethodName: "VolumeUpdate",
			Handler:    _Director_VolumeUpdate_Handler,
		},
		{
			MethodName: "VolumeDelete",
			Handler:    _Director_VolumeDelete_Handler,
		},
		{
			MethodName: "VolumeList",
			Handler:    _Director_VolumeList_Handler,
		},
		{
			MethodName: "PresentationCreate",
			Handler:    _Director_PresentationCreate_Handler,
		},
		{
			MethodName: "PresentationUpdate",
			Handler:    _Director_PresentationUpdate_Handler,
		},
		{
			MethodName: "PresentationDelete",
			Handler:    _Director_PresentationDelete_Handler,
		},
		{
			MethodName: "PresentationList",
			Handler:    _Director_PresentationList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "director.proto",
}

func init() { proto.RegisterFile("director.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x6a, 0x1a, 0x4f,
	0x18, 0x8d, 0x1a, 0x8d, 0x7e, 0xfe, 0xf9, 0x85, 0x21, 0xbf, 0x66, 0x59, 0x09, 0x31, 0x43, 0x43,
	0x25, 0x17, 0x42, 0x0c, 0x85, 0x96, 0x5e, 0x2a, 0xb4, 0x4b, 0x0a, 0x4d, 0xa7, 0xa4, 0xb7, 0xb2,
	0x9d, 0x9d, 0x84, 0x01, 0xdd, 0xd9, 0xcc, 0xcc, 0x5a, 0x0a, 0x7d, 0xb8, 0xbe, 0x46, 0xdf, 0xa6,
	0xec, 0xcc, 0xae, 0x8e, 0x31, 0xd1, 0xb6, 0xe9, 0x9d, 0x9e, 0x33, 0xe7, 0xf8, 0xcd, 0x39, 0xdf,
	0x20, 0x74, 0x22, 0x2e, 0x19, 0xd5, 0x42, 0x0e, 0x12, 0x29, 0xb4, 0x40, 0xcd, 0xc5, 0xf7, 0xf9,
	0xb9, 0xdf, 0xa2, 0x62, 0x36, 0x13, 0xb1, 0xa5, 0xf0, 0x21, 0xfc, 0x3f, 0xce, 0xc9, 0x4f, 0x3a,
	0xd4, 0xa9, 0x22, 0xec, 0x2e, 0x65, 0x4a, 0xe3, 0x0b, 0xe8, 0xac, 0x12, 0xe8, 0x04, 0x5a, 0x73,
	0x26, 0x15, 0x17, 0xf1, 0x84, 0xc7, 0x37, 0xc2, 0x2b, 0xf5, 0x4a, 0xfd, 0x06, 0x69, 0xe6, 0x58,
	0x10, 0xdf, 0x08, 0xfc, 0x0a, 0x0e, 0x0b, 0xd1, 0x67, 0x31, 0x4d, 0x67, 0xec, 0x3d, 0x57, 0xfa,
	0x63, 0xca, 0xe4, 0x37, 0x74, 0x04, 0x30, 0x37, 0xd0, 0x84, 0x47, 0xca, 0x2b, 0xf5, 0x2a, 0xfd,
	0x36, 0x69, 0x58, 0x24, 0x88, 0x14, 0xf6, 0xc1, 0x5b, 0x55, 0x66, 0x3f, 0xca, 0x95, 0xe6, 0x54,
	0xe1, 0x67, 0x70, 0xb0, 0xce, 0xa5, 0x0a, 0xff, 0x28, 0x2f, 0x67, 0xb4, 0x04, 0x3a, 0x83, 0x32,
	0xa5, 0x66, 0xb2, 0xe6, 0xd0, 0x1f, 0xe4, 0x37, 0x9d, 0x9f, 0x0f, 0xc6, 0xa1, 0x0e, 0x93, 0x69,
	0x18, 0xb3, 0x91, 0x81, 0x48, 0x99, 0x52, 0xd4, 0x85, 0xc6, 0x62, 0x22, 0xaf, 0xdc, 0x2b, 0xf5,
	0xdb, 0xa4, 0x5e, 0x0c, 0x94, 0x8d, 0xfb, 0x55, 0x72, 0xcd, 0x26, 0x09, 0x4f, 0x98, 0x57, 0x31,
	0x6c, 0xc3, 0x20, 0x57, 0x3c, 0x61, 0x99, 0x56, 0xb2, 0x30, 0xb2, 0xec, 0xae, 0xd5, 0x66, 0x80,
	0x21, 0xf7, 0xa1, 0x72, 0x27, 0x94, 0x57, 0xed, 0x95, 0xfa, 0xbb, 0x24, 0xfb, 0x88, 0x8e, 0xa1,
	0x29, 0x59, 0x32, 0xe5, 0x34, 0x34, 0xb7, 0xaf, 0x99, 0xdb, 0x43, 0x0e, 0x05, 0x91, 0x42, 0x6f,
	0xa0, 0xaa, 0x74, 0xa8, 0x95, 0xb7, 0x67, 0x46, 0x3f, 0x1d, 0x38, 0x8d, 0x0d, 0x1e, 0x0b, 0x86,
	0x58, 0x0d, 0x7a, 0x0d, 0x35, 0x65, 0x12, 0xf1, 0xea, 0x46, 0x7d, 0xb2, 0x45, 0x9d, 0x2a, 0x92,
	0x0b, 0xf0, 0x25, 0xa0, 0xf5, 0xc2, 0xd0, 0x4b, 0xd8, 0xb3, 0x41, 0xd8, 0xa2, 0x9a, 0xc3, 0xee,
	0x06, 0x47, 0x52, 0x9c, 0xc5, 0xef, 0xe0, 0xa8, 0xa0, 0xae, 0x24, 0x53, 0x2c, 0xce, 0x26, 0x15,
	0xf1, 0x72, 0x07, 0x5e, 0xc0, 0x7f, 0x89, 0x43, 0x64, 0xb9, 0xdb, 0x45, 0xe8, 0xb8, 0x70, 0x10,
	0xe1, 0xef, 0xcb, 0xc6, 0x5d, 0xa7, 0x3f, 0xad, 0x57, 0x89, 0x54, 0x52, 0xb7, 0x5e, 0x0b, 0x04,
	0x51, 0x46, 0xea, 0x50, 0xde, 0x32, 0x9d, 0x91, 0xb6, 0xdd, 0xba, 0x05, 0x82, 0x08, 0xd3, 0xe5,
	0x2e, 0xde, 0xbf, 0x07, 0x7a, 0x0b, 0x6d, 0x77, 0xd6, 0x22, 0xa0, 0x87, 0x23, 0x77, 0xd5, 0x64,
	0x55, 0x37, 0xfc, 0x59, 0x85, 0x7a, 0x71, 0x0e, 0x5d, 0x42, 0x2d, 0x7f, 0x64, 0xf8, 0x41, 0xa3,
	0x95, 0xa7, 0xe9, 0x77, 0x37, 0x9c, 0xc1, 0x3b, 0x68, 0x04, 0x2d, 0xdb, 0xcc, 0x48, 0xb2, 0x50,
	0x33, 0xb4, 0xa9, 0x3c, 0xff, 0xc0, 0x49, 0x91, 0x24, 0x94, 0x30, 0x95, 0x4e, 0xb5, 0x6b, 0x72,
	0x9d, 0x44, 0x4f, 0x37, 0x19, 0xb3, 0x29, 0xfb, 0x5b, 0x93, 0x6b, 0x00, 0x67, 0x35, 0x9f, 0x6f,
	0xb0, 0x58, 0x2c, 0x9a, 0x7f, 0xbc, 0xe5, 0x14, 0xde, 0x41, 0x1f, 0x00, 0xb9, 0xf5, 0xe4, 0x59,
	0x6d, 0xef, 0xf1, 0xd1, 0x39, 0xef, 0x19, 0xe6, 0xb9, 0xfd, 0x3b, 0xc3, 0x3c, 0xc3, 0x27, 0x18,
	0xde, 0xc2, 0xfe, 0xda, 0x3e, 0x9f, 0x6d, 0xb5, 0x5b, 0xa6, 0x7a, 0xfa, 0x5b, 0x67, 0xf1, 0xce,
	0x97, 0x9a, 0xf9, 0x6f, 0xb9, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x14, 0xbe, 0xab, 0x88,
	0x06, 0x00, 0x00,
}
