// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: director.proto
#ifndef GRPC_director_2eproto__INCLUDED
#define GRPC_director_2eproto__INCLUDED

#include "director.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace director {
namespace v1 {

// *
// Director configuration and status service.
class Director final {
 public:
  static constexpr char const* service_full_name() {
    return "director.v1.Director";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // *
    // Add configuration for the given DirectorVolume message.
    //
    // @return  RpcResult
    virtual ::grpc::Status VolumeCreate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::common::v1::RpcResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>> AsyncVolumeCreate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>>(AsyncVolumeCreateRaw(context, request, cq));
    }
    // *
    // Update configuration for the given DirectorVolume message.
    //
    // @return  RpcResult
    virtual ::grpc::Status VolumeUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::common::v1::RpcResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>> AsyncVolumeUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>>(AsyncVolumeUpdateRaw(context, request, cq));
    }
    // *
    // Remove configuration for the given DirectorVolume message.
    //
    // returns RpcResult
    virtual ::grpc::Status VolumeDelete(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::common::v1::RpcResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>> AsyncVolumeDelete(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>>(AsyncVolumeDeleteRaw(context, request, cq));
    }
    // *
    // List configured volumes, optionally filtered using a DirectorVolumeListQuery
    // message.
    //
    // returns  A DirectorVolumeList message containing DirectorVolume objects,
    //          if any are found matching the filter
    virtual ::grpc::Status VolumeList(::grpc::ClientContext* context, const ::director::v1::DirectorVolumeListQuery& request, ::director::v1::DirectorVolumeList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::director::v1::DirectorVolumeList>> AsyncVolumeList(::grpc::ClientContext* context, const ::director::v1::DirectorVolumeListQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::director::v1::DirectorVolumeList>>(AsyncVolumeListRaw(context, request, cq));
    }
    // *
    // Add configuration for a Presentation volume specified in the DirectorPresentation message.
    //
    // returns RpcResult
    virtual ::grpc::Status PresentationCreate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::common::v1::RpcResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>> AsyncPresentationCreate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>>(AsyncPresentationCreateRaw(context, request, cq));
    }
    // *
    // Update configuration for a Presentation volume specified in the DirectorPresentation message.
    //
    // returns RpcResult
    virtual ::grpc::Status PresentationUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::common::v1::RpcResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>> AsyncPresentationUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>>(AsyncPresentationUpdateRaw(context, request, cq));
    }
    // *
    // Remove configuration for the Presentation volume specified in the DirectorPresentation message.
    //
    // returns RpcResult
    virtual ::grpc::Status PresentationDelete(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::common::v1::RpcResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>> AsyncPresentationDelete(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>>(AsyncPresentationDeleteRaw(context, request, cq));
    }
    // *
    // List configured Presentation volumes, optionally filtered using a DirectorPresentationListQuery
    // message.
    //
    // returns A DirectorPresentationList message containing DirectorPresentation mesages,
    //         if any are found matching the filter.
    virtual ::grpc::Status PresentationList(::grpc::ClientContext* context, const ::director::v1::DirectorPresentationListQuery& request, ::director::v1::DirectorPresentationList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::director::v1::DirectorPresentationList>> AsyncPresentationList(::grpc::ClientContext* context, const ::director::v1::DirectorPresentationListQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::director::v1::DirectorPresentationList>>(AsyncPresentationListRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>* AsyncVolumeCreateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>* AsyncVolumeUpdateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>* AsyncVolumeDeleteRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::director::v1::DirectorVolumeList>* AsyncVolumeListRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolumeListQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>* AsyncPresentationCreateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>* AsyncPresentationUpdateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::v1::RpcResult>* AsyncPresentationDeleteRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::director::v1::DirectorPresentationList>* AsyncPresentationListRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentationListQuery& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status VolumeCreate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::common::v1::RpcResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>> AsyncVolumeCreate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>>(AsyncVolumeCreateRaw(context, request, cq));
    }
    ::grpc::Status VolumeUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::common::v1::RpcResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>> AsyncVolumeUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>>(AsyncVolumeUpdateRaw(context, request, cq));
    }
    ::grpc::Status VolumeDelete(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::common::v1::RpcResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>> AsyncVolumeDelete(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>>(AsyncVolumeDeleteRaw(context, request, cq));
    }
    ::grpc::Status VolumeList(::grpc::ClientContext* context, const ::director::v1::DirectorVolumeListQuery& request, ::director::v1::DirectorVolumeList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::director::v1::DirectorVolumeList>> AsyncVolumeList(::grpc::ClientContext* context, const ::director::v1::DirectorVolumeListQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::director::v1::DirectorVolumeList>>(AsyncVolumeListRaw(context, request, cq));
    }
    ::grpc::Status PresentationCreate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::common::v1::RpcResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>> AsyncPresentationCreate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>>(AsyncPresentationCreateRaw(context, request, cq));
    }
    ::grpc::Status PresentationUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::common::v1::RpcResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>> AsyncPresentationUpdate(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>>(AsyncPresentationUpdateRaw(context, request, cq));
    }
    ::grpc::Status PresentationDelete(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::common::v1::RpcResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>> AsyncPresentationDelete(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>>(AsyncPresentationDeleteRaw(context, request, cq));
    }
    ::grpc::Status PresentationList(::grpc::ClientContext* context, const ::director::v1::DirectorPresentationListQuery& request, ::director::v1::DirectorPresentationList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::director::v1::DirectorPresentationList>> AsyncPresentationList(::grpc::ClientContext* context, const ::director::v1::DirectorPresentationListQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::director::v1::DirectorPresentationList>>(AsyncPresentationListRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>* AsyncVolumeCreateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>* AsyncVolumeUpdateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>* AsyncVolumeDeleteRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolume& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::director::v1::DirectorVolumeList>* AsyncVolumeListRaw(::grpc::ClientContext* context, const ::director::v1::DirectorVolumeListQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>* AsyncPresentationCreateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>* AsyncPresentationUpdateRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::common::v1::RpcResult>* AsyncPresentationDeleteRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentation& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::director::v1::DirectorPresentationList>* AsyncPresentationListRaw(::grpc::ClientContext* context, const ::director::v1::DirectorPresentationListQuery& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_VolumeCreate_;
    const ::grpc::RpcMethod rpcmethod_VolumeUpdate_;
    const ::grpc::RpcMethod rpcmethod_VolumeDelete_;
    const ::grpc::RpcMethod rpcmethod_VolumeList_;
    const ::grpc::RpcMethod rpcmethod_PresentationCreate_;
    const ::grpc::RpcMethod rpcmethod_PresentationUpdate_;
    const ::grpc::RpcMethod rpcmethod_PresentationDelete_;
    const ::grpc::RpcMethod rpcmethod_PresentationList_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // *
    // Add configuration for the given DirectorVolume message.
    //
    // @return  RpcResult
    virtual ::grpc::Status VolumeCreate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response);
    // *
    // Update configuration for the given DirectorVolume message.
    //
    // @return  RpcResult
    virtual ::grpc::Status VolumeUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response);
    // *
    // Remove configuration for the given DirectorVolume message.
    //
    // returns RpcResult
    virtual ::grpc::Status VolumeDelete(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response);
    // *
    // List configured volumes, optionally filtered using a DirectorVolumeListQuery
    // message.
    //
    // returns  A DirectorVolumeList message containing DirectorVolume objects,
    //          if any are found matching the filter
    virtual ::grpc::Status VolumeList(::grpc::ServerContext* context, const ::director::v1::DirectorVolumeListQuery* request, ::director::v1::DirectorVolumeList* response);
    // *
    // Add configuration for a Presentation volume specified in the DirectorPresentation message.
    //
    // returns RpcResult
    virtual ::grpc::Status PresentationCreate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response);
    // *
    // Update configuration for a Presentation volume specified in the DirectorPresentation message.
    //
    // returns RpcResult
    virtual ::grpc::Status PresentationUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response);
    // *
    // Remove configuration for the Presentation volume specified in the DirectorPresentation message.
    //
    // returns RpcResult
    virtual ::grpc::Status PresentationDelete(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response);
    // *
    // List configured Presentation volumes, optionally filtered using a DirectorPresentationListQuery
    // message.
    //
    // returns A DirectorPresentationList message containing DirectorPresentation mesages,
    //         if any are found matching the filter.
    virtual ::grpc::Status PresentationList(::grpc::ServerContext* context, const ::director::v1::DirectorPresentationListQuery* request, ::director::v1::DirectorPresentationList* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_VolumeCreate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_VolumeCreate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_VolumeCreate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeCreate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVolumeCreate(::grpc::ServerContext* context, ::director::v1::DirectorVolume* request, ::grpc::ServerAsyncResponseWriter< ::common::v1::RpcResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VolumeUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_VolumeUpdate() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_VolumeUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVolumeUpdate(::grpc::ServerContext* context, ::director::v1::DirectorVolume* request, ::grpc::ServerAsyncResponseWriter< ::common::v1::RpcResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VolumeDelete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_VolumeDelete() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_VolumeDelete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeDelete(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVolumeDelete(::grpc::ServerContext* context, ::director::v1::DirectorVolume* request, ::grpc::ServerAsyncResponseWriter< ::common::v1::RpcResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_VolumeList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_VolumeList() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_VolumeList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeList(::grpc::ServerContext* context, const ::director::v1::DirectorVolumeListQuery* request, ::director::v1::DirectorVolumeList* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVolumeList(::grpc::ServerContext* context, ::director::v1::DirectorVolumeListQuery* request, ::grpc::ServerAsyncResponseWriter< ::director::v1::DirectorVolumeList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PresentationCreate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PresentationCreate() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_PresentationCreate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationCreate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPresentationCreate(::grpc::ServerContext* context, ::director::v1::DirectorPresentation* request, ::grpc::ServerAsyncResponseWriter< ::common::v1::RpcResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PresentationUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PresentationUpdate() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_PresentationUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPresentationUpdate(::grpc::ServerContext* context, ::director::v1::DirectorPresentation* request, ::grpc::ServerAsyncResponseWriter< ::common::v1::RpcResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PresentationDelete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PresentationDelete() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_PresentationDelete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationDelete(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPresentationDelete(::grpc::ServerContext* context, ::director::v1::DirectorPresentation* request, ::grpc::ServerAsyncResponseWriter< ::common::v1::RpcResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PresentationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_PresentationList() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_PresentationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationList(::grpc::ServerContext* context, const ::director::v1::DirectorPresentationListQuery* request, ::director::v1::DirectorPresentationList* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPresentationList(::grpc::ServerContext* context, ::director::v1::DirectorPresentationListQuery* request, ::grpc::ServerAsyncResponseWriter< ::director::v1::DirectorPresentationList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_VolumeCreate<WithAsyncMethod_VolumeUpdate<WithAsyncMethod_VolumeDelete<WithAsyncMethod_VolumeList<WithAsyncMethod_PresentationCreate<WithAsyncMethod_PresentationUpdate<WithAsyncMethod_PresentationDelete<WithAsyncMethod_PresentationList<Service > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_VolumeCreate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_VolumeCreate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_VolumeCreate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeCreate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VolumeUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_VolumeUpdate() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_VolumeUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VolumeDelete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_VolumeDelete() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_VolumeDelete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeDelete(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_VolumeList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_VolumeList() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_VolumeList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status VolumeList(::grpc::ServerContext* context, const ::director::v1::DirectorVolumeListQuery* request, ::director::v1::DirectorVolumeList* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PresentationCreate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PresentationCreate() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_PresentationCreate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationCreate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PresentationUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PresentationUpdate() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_PresentationUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PresentationDelete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PresentationDelete() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_PresentationDelete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationDelete(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PresentationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_PresentationList() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_PresentationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PresentationList(::grpc::ServerContext* context, const ::director::v1::DirectorPresentationListQuery* request, ::director::v1::DirectorPresentationList* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VolumeCreate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_VolumeCreate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorVolume, ::common::v1::RpcResult>(std::bind(&WithStreamedUnaryMethod_VolumeCreate<BaseClass>::StreamedVolumeCreate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_VolumeCreate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VolumeCreate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVolumeCreate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorVolume,::common::v1::RpcResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VolumeUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_VolumeUpdate() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorVolume, ::common::v1::RpcResult>(std::bind(&WithStreamedUnaryMethod_VolumeUpdate<BaseClass>::StreamedVolumeUpdate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_VolumeUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VolumeUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVolumeUpdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorVolume,::common::v1::RpcResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VolumeDelete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_VolumeDelete() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorVolume, ::common::v1::RpcResult>(std::bind(&WithStreamedUnaryMethod_VolumeDelete<BaseClass>::StreamedVolumeDelete, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_VolumeDelete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VolumeDelete(::grpc::ServerContext* context, const ::director::v1::DirectorVolume* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVolumeDelete(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorVolume,::common::v1::RpcResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_VolumeList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_VolumeList() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorVolumeListQuery, ::director::v1::DirectorVolumeList>(std::bind(&WithStreamedUnaryMethod_VolumeList<BaseClass>::StreamedVolumeList, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_VolumeList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status VolumeList(::grpc::ServerContext* context, const ::director::v1::DirectorVolumeListQuery* request, ::director::v1::DirectorVolumeList* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVolumeList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorVolumeListQuery,::director::v1::DirectorVolumeList>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PresentationCreate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PresentationCreate() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorPresentation, ::common::v1::RpcResult>(std::bind(&WithStreamedUnaryMethod_PresentationCreate<BaseClass>::StreamedPresentationCreate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PresentationCreate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PresentationCreate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPresentationCreate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorPresentation,::common::v1::RpcResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PresentationUpdate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PresentationUpdate() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorPresentation, ::common::v1::RpcResult>(std::bind(&WithStreamedUnaryMethod_PresentationUpdate<BaseClass>::StreamedPresentationUpdate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PresentationUpdate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PresentationUpdate(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPresentationUpdate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorPresentation,::common::v1::RpcResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PresentationDelete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PresentationDelete() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorPresentation, ::common::v1::RpcResult>(std::bind(&WithStreamedUnaryMethod_PresentationDelete<BaseClass>::StreamedPresentationDelete, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PresentationDelete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PresentationDelete(::grpc::ServerContext* context, const ::director::v1::DirectorPresentation* request, ::common::v1::RpcResult* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPresentationDelete(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorPresentation,::common::v1::RpcResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PresentationList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_PresentationList() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::StreamedUnaryHandler< ::director::v1::DirectorPresentationListQuery, ::director::v1::DirectorPresentationList>(std::bind(&WithStreamedUnaryMethod_PresentationList<BaseClass>::StreamedPresentationList, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_PresentationList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PresentationList(::grpc::ServerContext* context, const ::director::v1::DirectorPresentationListQuery* request, ::director::v1::DirectorPresentationList* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPresentationList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::director::v1::DirectorPresentationListQuery,::director::v1::DirectorPresentationList>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_VolumeCreate<WithStreamedUnaryMethod_VolumeUpdate<WithStreamedUnaryMethod_VolumeDelete<WithStreamedUnaryMethod_VolumeList<WithStreamedUnaryMethod_PresentationCreate<WithStreamedUnaryMethod_PresentationUpdate<WithStreamedUnaryMethod_PresentationDelete<WithStreamedUnaryMethod_PresentationList<Service > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_VolumeCreate<WithStreamedUnaryMethod_VolumeUpdate<WithStreamedUnaryMethod_VolumeDelete<WithStreamedUnaryMethod_VolumeList<WithStreamedUnaryMethod_PresentationCreate<WithStreamedUnaryMethod_PresentationUpdate<WithStreamedUnaryMethod_PresentationDelete<WithStreamedUnaryMethod_PresentationList<Service > > > > > > > > StreamedService;
};

}  // namespace v1
}  // namespace director


#endif  // GRPC_director_2eproto__INCLUDED
